apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stranded-autoscaler-node-alerter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stranded-autoscaler-node-alerter
subjects:
  - kind: ServiceAccount
    name: stranded-autoscaler-node-alerter
    namespace: observability
