---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - secret-store.yaml
  - oci-repository.yaml
  - flux-kustomization.yaml
