apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
  - source:
      kind: ConfigMap
      version: v1
      namespace: arc-ksail-analysis
      fieldPath: metadata.name
    targets:
      - select:
          kind: HelmRelease
          name: ksail-analysis-runners
          namespace: arc-ksail-analysis
        fieldPaths:
          - spec.values.template.spec.volumes.[name=runner-metrics].configMap.name
resources:
  - config-map-job-metrics.yaml
  - oci-repository.yaml
  - helm-release.yaml
  - external-secret.yaml
  - secret-store.yaml
  - service-account.yaml
  - cilium-network-policy-runner.yaml
