apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: whoami
  namespace: whoami
spec:
  hosts:
    - whoami.${domain}
  scaleTargetRef:
    name: whoami
    kind: Deployment
    apiVersion: apps/v1
    service: whoami
    port: 80
  replicas:
    min: 0
    max: ${whoami_max_replicas:=2}
  scaledownPeriod: 300
  scalingMetric:
    concurrency:
      targetValue: 10
