---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-proxy/
  - cdi/
  - cert-manager/
  - cilium/
  - cloudnative-pg/
  - dex/
  - external-secrets/
  - flux-operator/
  - keda/
  - keda-http-add-on/
  - kube-prometheus-stack/
  - kubevirt/
  - kubescape/
  - kyverno/
  - metrics-server/
  - oauth2-proxy/
  - openbao/
  - opencost/
  - reloader/
  - trust-manager/
  - velero/
  - vertical-pod-autoscaler/
