---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/helm-test: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  chart:
    spec:
      chart: cilium
      version: 1.19.3
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 10m0s
  # https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
  values:
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: localhost
    k8sServicePort: 7445
    hubble:
      relay:
        replicas: ${cilium_replicas:=2}
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
          # Chart defaults set maxUnavailable: 1; PDB can't have both set.
          maxUnavailable: null
      ui:
        replicas: ${cilium_replicas:=2}
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
          maxUnavailable: null
    operator:
      replicas: ${cilium_replicas:=2}
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
        maxUnavailable: null
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
    clustermesh:
      apiserver:
        replicas: ${cilium_replicas:=2}
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    authentication:
      enabled: true
      mutual:
        spire:
          enabled: true
          install:
            namespace: kube-system
            existingNamespace: true
            # TODO: Remove workaround when SPIRE no longer fails to start (https://github.com/cilium/cilium/issues/40533)
            server:
              initContainers:
              - command:
                - /bin/sh
                - -c
                - |
                  chown -R 1000:1000 /run/spire/data
                  chown -R 1000:1000 /tmp/spire-server
                image: docker.io/library/busybox:1.37.0
                imagePullPolicy: IfNotPresent
                name: chown
                securityContext:
                  runAsGroup: 0
                  runAsUser: 0
                volumeMounts:
                - mountPath: /run/spire/data
                  name: spire-data
                - mountPath: /tmp/spire-server/private
                  name: spire-server-socket
              securityContext:
                runAsGroup: 1000
                runAsUser: 1000
    gatewayAPI:
      enabled: true
      enableAlpn: true
