apiVersion: v1
kind: Secret
metadata:
    name: crossview-credentials
    namespace: crossview
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:l97/HGTe2II77cYTMRSpEfjEUJC+gfgijcGdHBmjiCM=,iv:nNsiu5DIVEpMXWWb9fedE04D4JpI0PkEua/xAVk3nug=,tag:0ipXNhSIjP3c2Cx0bg2ChQ==,type:str]
    session-secret: ENC[AES256_GCM,data:U8TQ6o6pdoNudIGTskZeSkiCQdaFAoTsiOaAFttvIaYcOVp+AhamY7guk20+6LI/TofreQlIuiNw+mBKBtJOPw==,iv:GWbCD7uoxUVWDS74JpNfeG7KjZvNt6Wkc5rhz2M88NQ=,tag:D7fGX1zdM7xukXmqywyz+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHblpIL3YrNFlwZFBSSity
            c3BUajhsdHlOMkwra0VNZmtxRVIxdTRZNEVjCkFsTC9iV3JYOGtVU0kvK1BzSG92
            Sm9TQ1dJMnhhbWIrTzluOC9ZSkJ6azgKLS0tIENQMnFMeXI4U2N4Z1JIbkxtUmt5
            RFpoemEyLzBiZFh3NFRnWXVDeDU3TVUKhtdD8nnGHufn61VZCb58TkDDIX3RsVAO
            8pmWTTGnH5RqKYgBICBx+1zkNquPVmgcD5c+tLRYjMH5Jtsx6BeGRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdzhIb21mTlFGdGhmblFM
            QW44d09Rb3NSQUF3QkdPRU9GWWdnUWNrNlZrCklRR0oydnl4dnR0RGZsZ1BzclUv
            UnJ4WFhLUW44bjVrdGxCRVp0eWlJUnMKLS0tIEoyVkYrNHNWSGF3eEwzNVRUdWFi
            UTNGV3JhdFlnTmhTUzlpaStmbWFhNzgKs961PyKpg+zBJPVk8WMaA/RehqpHCVQP
            C8p8bVRcSky34+iqZhOqeHtbmvyZeBBCNYbfY86OSHrU9zGTY1Wf9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T20:14:53Z"
    mac: ENC[AES256_GCM,data:XypfwcwvokeYaR7yx7FrVTfxbK2Voz4kt6yG+MQNgY5jiCgh01CsusagqBMMlyLeqVB36TzUKdtKpspAlKnji3ctV6gRGVZB81nJmmT25z5exanMfp3XOFoD92Ul/fUyFsKObQG3NY94Vor1eazde4UqDiXcX8JGyqaq13MprLY=,iv:++SQXpUVS8U9upJKfgKQ1U5TWCZ5jcWwcsS63UhixR4=,tag:AEU9dVsbCJVPv2sc3VJ94w==,type:str]
    version: 3.13.1
