---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fleet-license
  namespace: fleetdm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fleet-license
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: apps/fleetdm/license
        property: license-key
