apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - helm-repository.yaml
  - httproute.yaml
  - http-scaled-object.yaml
  - external-secrets.yaml
  - external-secrets-serviceaccount.yaml
  - mysql-static-cred-generator.yaml
  - server-key-external-secret.yaml
  - networkpolicy.yaml
  - pod-disruption-budget.yaml
  - mysql-primary-service.yaml
