kind: Secret
apiVersion: v1
metadata:
  name: mysql
  namespace: fleetdm
stringData:
  mysql-root-password: ${fleetdm_mysql_root_password}
  mysql-replication-password: ${fleetdm_mysql_replication_password}
  mysql-password: ${fleetdm_mysql_password}
