apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: kubescape
spec:
  values:
    capabilities:
      vulnerabilityScan: disable
      runtimeDetection: disable
