apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:background-controller:mutate-longhorn-csi-plugin
  namespace: longhorn-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno:background-controller:mutate-longhorn-csi-plugin
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
