---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: umami-app-secret
  namespace: openbao
spec:
  length: 64
  digits: 16
  symbols: 0
  noUpper: false
  allowRepeat: true
