---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: fleetdm-mysql-password
  namespace: openbao
spec:
  length: 24
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
