---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-umami-app-secret
  namespace: openbao
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: generated-umami-app-secret
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/umami/app
          property: app-secret
