---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-fleetdm-server-key
  namespace: openbao
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: generated-fleetdm-server-private-key
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/fleetdm/server
          property: private-key
