---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seed-oauth2-proxy-cookie-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: variables-cluster
  data:
    - match:
        secretKey: oauth2_proxy_cookie_secret
        remoteRef:
          remoteKey: infrastructure/oidc/oauth2-proxy
          property: cookie-secret
