---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-fleetdm-mysql-replication-password
  namespace: openbao
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: generated-fleetdm-mysql-replication-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/fleetdm/mysql
          property: mysql-replication-password
