---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-crossview-admin-password
  namespace: openbao
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: generated-crossview-admin-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/crossview/admin
          property: admin-password
