---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../bases/infrastructure/controllers/
  - coredns/
  - flux-instance/
  - minio/
patches:
  - target:
      kind: HelmRelease
      name: cilium
      namespace: kube-system
    path: cilium/patches/helm-release-patch.yaml
  - target:
      kind: HelmRelease
      name: metrics-server
      namespace: kube-system
    path: metrics-server/patches/helm-release-patch.yaml
  - target:
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
    path: flux-operator/patches/helm-release-patch.yaml
  - target:
      kind: HelmRelease
      name: kubescape
      namespace: kubescape
    path: kubescape/patches/helm-release-patch.yaml
