---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-key-secret.enc.yaml
  - pushsecret.yaml
  - external-secret.yaml
  - git-repository.yaml
  - image-update-automation.yaml
