#!/usr/bin/env bash
#
# Pins the default-deny CiliumNetworkPolicy that add-default-deny generates into
# every namespace to the one shape that is both VALID and allows NOTHING:
#
#   endpointSelector: {}            every endpoint in the namespace
#   ingress: [{}] / egress: [{}]    one empty rule per direction: no peer, no port
#   enableDefaultDeny: both true    default-deny by selection
#   no ingressDeny / egressDeny     an explicit deny would override every allow
#                                   policy in the namespace (#3404)
#
# The production rule suite (require-generated-cilium-policy-rules) proves the
# shape is valid — `ingress: []` was rejected by Cilium for ~101 days (#3501).
# This pins what it DOES, and that every copy of it agrees:
#   1. the generate data in the ClusterPolicy;
#   2. what the Kyverno CLI actually generates from it, so an empty rule that
#      templating dropped would show up here rather than in prod;
#   3. the copy Flux applies under the same name in oauth2-proxy — two field
#      managers writing different values would overwrite each other forever;
#   4. the verbatim generated body the tenant boundary test exercises.

set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly root_dir
readonly policy="${root_dir}/k8s/bases/infrastructure/cluster-policies/best-practices/add-default-deny.yaml"
readonly flux_copy="${root_dir}/k8s/bases/infrastructure/controllers/oauth2-proxy/cilium-network-policy-default-deny.yaml"
readonly tenant_fixture="${root_dir}/tests/restrict-tenant-network-policies/kyverno-author/resources.yaml"
readonly want='{"egress":[{}],"enableDefaultDeny":{"egress":true,"ingress":true},"endpointSelector":{},"ingress":[{}]}'

work="$(mktemp -d)"
readonly work
trap 'rm -rf "${work}"' EXIT

failures=0

# Compares one spec (JSON) to the pinned shape, key order ignored.
matches() {
  local got
  got="$(printf '%s' "$1" | jq -cS .)" || return 1
  [ "${got}" = "${want}" ]
}

check() {
  local what="$1" spec="$2"
  if [ -z "${spec}" ] || [ "${spec}" = "null" ]; then
    printf 'FAIL: %s: no default-deny spec found — nothing was checked\n' "${what}" >&2
    failures=$((failures + 1))
  elif ! matches "${spec}"; then
    printf 'FAIL: %s\n  want %s\n  got  %s\n' "${what}" "${want}" "$(printf '%s' "${spec}" | jq -cS .)" >&2
    failures=$((failures + 1))
  fi
}

# Negative controls: the comparison must refuse the shape that shipped before
# #3501, a peer that allows the whole namespace, and an explicit deny — or a
# pass below proves nothing.
for wrong in \
  '{"endpointSelector":{},"ingress":[],"egress":[],"enableDefaultDeny":{"ingress":true,"egress":true}}' \
  '{"endpointSelector":{},"ingress":[{"fromEndpoints":[{}]}],"egress":[{}],"enableDefaultDeny":{"ingress":true,"egress":true}}' \
  '{"endpointSelector":{},"ingress":[{}],"egress":[{}],"egressDeny":[{"toEntities":["world"]}],"enableDefaultDeny":{"ingress":true,"egress":true}}'; do
  if matches "${wrong}"; then
    printf 'FAIL: the comparison accepted a wrong shape: %s\n' "${wrong}" >&2
    exit 1
  fi
done

# 1. The generate data as committed.
check 'generate-default-deny data in add-default-deny.yaml' "$(yq -o=json -I=0 \
  '.spec.rules[] | select(.name == "generate-default-deny") | .generate.data.spec' "${policy}")"

# 2. What Kyverno generates from it for a namespace.
printf 'apiVersion: v1\nkind: Namespace\nmetadata:\n  name: probe\n' >"${work}/namespace.yaml"
if ! kyverno apply "${policy}" --resource "${work}/namespace.yaml" -o "${work}/generated" \
  >"${work}/apply.log" 2>&1; then
  printf 'FAIL: kyverno apply failed:\n' >&2
  cat "${work}/apply.log" >&2
  exit 1
fi
generated="$(cat "${work}"/generated/*.yaml 2>/dev/null | yq -o=json -I=0 \
  'select(.kind == "CiliumNetworkPolicy" and .metadata.name == "default-deny" and .metadata.namespace == "probe") | .spec')"
[ "$(printf '%s\n' "${generated}" | grep -c .)" -eq 1 ] || {
  printf 'FAIL: expected exactly one generated default-deny CiliumNetworkPolicy, got:\n%s\n' "${generated}" >&2
  exit 1
}
check 'default-deny generated by the Kyverno CLI' "${generated}"

# 3. The copy Flux applies under the same name.
check 'oauth2-proxy CiliumNetworkPolicy default-deny (Flux)' "$(yq -o=json -I=0 '.spec' "${flux_copy}")"

# 4. The body the tenant boundary test treats as the generated floor.
check 'generated body in the tenant boundary fixture' "$(yq -o=json -I=0 \
  'select(.kind == "CiliumNetworkPolicy" and .metadata.name == "default-deny") | .spec' "${tenant_fixture}")"

if [ "${failures}" -gt 0 ]; then
  printf '%d default-deny cop(y/ies) differ from the pinned deny-by-selection shape\n' "${failures}" >&2
  exit 1
fi
printf 'PASS: every default-deny copy is the valid deny-by-selection shape\n'
