apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
    namespace: wedding-app
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fXdFPwYHDSiY,iv:swOT4rtBRJCYA+JdaQioB4WVoLy7lG+ObUfJfgXG/Os=,tag:Dj21RzLpukxACJMWdwbNIA==,type:str]
    password: ENC[AES256_GCM,data:mouAVVjLbCYrN+NBgQ==,iv:mrO+hncbxJSnUmF+W0VHiB7amYZrDzm+OZu2gphXin0=,tag:TeBOrkWdXkR6tVgyOtiX8A==,type:str]
sops:
    age:
        - recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVUliRElOYkVOQUVZbHpO
            K1kxZTB6MXZjMlViQ0JBaTZSSWZoc3NXVWg4CmJHbDZ4akM4bnpwRXdnSlRRaHVE
            REdkbnpGMWlGMXYrVzJ5Z3RlUURDWW8KLS0tIElzcmpLS0ZTUjd3eHBTeThkQmM0
            ZzFnYXZZckVJS1F0RS9XZ0NYTHJoNWcK703Ek/LSRPlJFQZXRvyPPX4+Mvp9+CsV
            V39bAA17wAJ3P4tkL03Urm0ev90D5MuIileVrztLwLKT1s7oZ6+5Yw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOEppRFZ1WGdTRHM3Rjds
            cDdIUzRNK3dtcjY2djVoamJJTDY2NHVqNEI4Ck81eW9jc2VabENvWWhmazVWWGQx
            bzV5M2hVb3NBcUdBdjY2N1pmUlJyZUUKLS0tIEtRZmFkUmRjT1F0ZDBOM3NNM01N
            cjRvRTN6RkhmK3FiZDhGZUpxM3NwWGMKBp7mhmYB5UH7XRg5oM0IMao44F/fEQo8
            c5vL9Xw+B8qQ2RYF5Yb85IbluL4iRrrcevEWSiQHCDMk7Ub8jwrE6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T19:33:27Z"
    mac: ENC[AES256_GCM,data:oU8FCtEjDms4df0b9PjObnOIgUKoEQC20Yq0F4uO/ELZuQoLQ/enrNrxATz4NY0oYhyjgb4mYItBmSabT5wrtTK97ED+1gDxOSkXW13PceOz9JVUkzDqKUd2dcudX5nHiZEqVxaqi46Kk3pEwZmnYYi3Fu2RUpewc38qMe1bpqc=,iv:v7pwYhwZ2HwKUfhSEeFfjHDttKguJ0ZuE50lfQRdZ8I=,tag:I+d+QUR13N9klnoDGAjSKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
