apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: wedding-app
type: Opaque
stringData:
  githubAppID: "${github_app_id}"
  githubAppInstallationID: "${github_app_installation_id}"
  githubAppPrivateKey: "${github_app_private_key}"
