apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: wedding-app
  namespace: wedding-app
spec:
  image: ghcr.io/devantler-tech/wedding-app
  interval: 5m
  secretRef:
    name: ghcr-auth
  exclusionList:
    - "^sha-"
