apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: ksail
  name: wedding-app
  namespace: wedding-app
automountServiceAccountToken: false
imagePullSecrets:
  - name: ghcr-auth
