apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: wedding-app
stringData:
    age.agekey: ENC[AES256_GCM,data:o0jD+pjedLPmVHQx/nbkVht2EJLF2ARw/8MF12BwLXD/CU8/JmEe9iWpYcwEK4FnlZIjop6PdpzD4XkfwwqnQCKsBiksprVy8/g=,iv:rL+mfsSfoDl5YA53rfn0A1k0UzwpKVa1X7YDkSu0qkY=,tag:IXo5c5L21oJisD9GE/p8Mg==,type:str]
sops:
    age:
        - recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZm01RklTb2FDMWdXcm00
            WTJkUFJ1SHBOSXNMWDBsRjI0dVVpRDJPSlVBCndFWHMvdkF0SHY2a1VPL3NncFp1
            M2RxWkIxR2FSb3BPZG5LeFo5RnhMVW8KLS0tIHJWNXNCVGpUMTg0QUxCMmI3eGMy
            UnBMM2I1TDdpMm5Td1NSRmMzbndwNTAKVH6R1ySleI2GVecOldN82uuGy29lWSbr
            nmOpK33XHCBrE3vE3qsqqETAObcdBoffXGWH3fKrVFE1Y8C0Ffv50w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRzFpTmRDOUplRGVFTFBN
            MGRIRGl4LzJCcU4vZ09VSEVzZUpHQ2UrS204CjcrcU5USjRxeDRiR1BsS3JyelI2
            UEo4VTNtNkVWZFpGRk14RzFYU1VCcTQKLS0tIGNkSGppSmRFK1UzZWtSbVUyQ1dw
            emRjNXp1Vjljb0NmdGltSVBXZ2QrMmMKdtMvFmAf/r3bp8UaDAjWqZ4cBGLm/wxq
            VkiUNnvheft9wTeeKB/J+w1PRGnF15Fb/coUBol+ovEooeWW1OCSCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T17:13:31Z"
    mac: ENC[AES256_GCM,data:KxbeU1SdUQhPh3AccqnPbBc1SS8B5mKRLNXE+1/hdGcyQKHlQeO3f5SEGmyss172cU8RHuuue0Rf9F548uoOEPiAaYrqv79M6hK3B81Tk6dwb9wXCDhDDTKOHci3v3FqyawWtCsRxlb4/CQl1W0g/jxhQNJI0n0ClZZ8In+j8F4=,iv:zLxw7X2cjdlH7wRq3oOKKdq7ZhQurIElyZNjLSsPtEA=,tag:7NoqoI8YPIkM26EQtJhagg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
