apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: wedding-app
stringData:
    age.agekey: ENC[AES256_GCM,data:3hOkmDuh/fX0ObWQ1h4XOFD2p8lw9QkgVyl8uEQEsvPAfu+LfrMMReVdmVO25WU+hf1Yo9Tnw4EJJGZOoTz465+/nlzdQk+dXGM=,iv:B807tsDUE1hW8oqne2DAer2bC/NjSN1xX/bjZpmt0bw=,tag:nngv333zY4dXvkYpomR0rg==,type:str]
sops:
    age:
        - recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN08zWVo4S0tKbStYanFX
            V25YMXlaVWFlbURaS0RnV1IyZjFoaHcxc0Q0CnROOW00VkdieEdLeWhTSU5TRFdq
            bXJNNWUwWS82dGVsRW9DODVGZUFwdHMKLS0tIGZjVFpVSkUzK21qOHhLM1lxV3g4
            SFRnTVlsQ2FkRjBadG5ScXZrTERRY2sK0fTujMqWIe7Wf8u2kkohnd/yEmN+UvBe
            tch5cRSmNooeTfiP2O7ab9r8xEFGlNeWiooqasOSl2HslnvKdCdQWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMHNaMUlxYTAvMlk0b1Qv
            enBWRllHS2c2L0FTU01QWjV1MnM1Yks5NmxJCld6aDhQTkdrTUd0dVI3OVJCY09z
            WXNOWThRc2FIUlFhRHlTTDgvY0R5UkkKLS0tIGlCWWliaTRzNXFuY1dKa0dYYWtq
            TmhXNnFkWC8rL2JzbEFWSkFVS0FhZ2sKrKRs5n9kUKjmra4PhNOXd/oPm4OxpzN0
            Ihnaq+8bVSsB3eMXvkF59d2tE5l6VZy2SMMLcyZC8oUJKF7sTI4HgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T19:31:49Z"
    mac: ENC[AES256_GCM,data:8eJGUyR1C/2WO8YGRA6+gPlKmbvG/irsyEsXKJ7uC8AG3mtesFnPt9uMUE4WIPTZi+5evd6xgJwzFqXPoxZlHT08yWNbbCuhodRmCQhMkxvotUKwwXiZwhjAQQaDBp5AqrxBTVHj9esWrOzluekWUs178n7gWxKU2YCY5RhOFGM=,iv:hl14sZAj4uLJtGPTiyguZ88+yn8Fl+FelmDBvqustHU=,tag:DX7ULK4MTjw41sG3uciFdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
