apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  labels:
    app.kubernetes.io/managed-by: ksail
  name: wedding-app
  namespace: wedding-app
spec:
  interval: 1m
  ref:
    tag: latest
  url: oci://ghcr.io/devantler-tech/wedding-app/manifests
  secretRef:
    name: ghcr-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/managed-by: ksail
  name: wedding-app
  namespace: wedding-app
spec:
  interval: 1m
  timeout: 5m
  retryInterval: 2m
  path: .
  prune: true
  wait: true
  force: true
  serviceAccountName: wedding-app
  sourceRef:
    kind: OCIRepository
    name: wedding-app
  targetNamespace: wedding-app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - target:
        kind: Deployment
        name: wedding-app
      patch: |
        - op: add
          path: /spec/template/spec/imagePullSecrets
          value:
            - name: ghcr-auth
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: ghcr.io/devantler-tech/wedding-app:latest
        - op: replace
          path: /spec/template/spec/containers/0/env/2
          value:
            name: DATABASE_URL
            value: "postgresql://${username}:${password}@wedding-db-rw:5432/wedding"
  postBuild:
    substituteFrom:
      - kind: Secret
        name: wedding-db-credentials
