---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns-networkpolicy.yaml
  - external-dns-rbac.yaml
  - ghcr-auth-externalsecret.yaml
  - namespace.yaml
  - rolebinding.yaml
  - secretstore.yaml
  - serviceaccount.yaml
  - sync.yaml
  - networkpolicy.yaml
