apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    helm.toolkit.fluxcd.io/helm-test: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 2m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  chart:
    spec:
      chart: headlamp
      version: 0.41.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: headlamp
            patch: |
              - op: add
                path: /metadata/annotations/secret.reloader.stakater.com~1reload
                value: oidc
              - op: add
                path: /spec/strategy
                value:
                  type: RollingUpdate
                  rollingUpdate:
                    maxSurge: 1
                    maxUnavailable: 0
  # https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/values.yaml
  values:
    replicaCount: ${headlamp_replicas:=2}
    podDisruptionBudget:
      enabled: true
      minAvailable: null
      maxUnavailable: 1
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: headlamp
            app.kubernetes.io/instance: headlamp
    config:
      oidc:
        clientID: public-client
        clientSecret: ${dex_client_secret}
        issuerURL: https://dex.${domain}
        scopes: "profile,email,groups"
    ingress:
      enabled: false
