// Generate the public metrics hook as a manifest the KSail publisher includes.
package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"os"

	"sigs.k8s.io/yaml"
)

const (
	scriptPath   = "scripts/ksail-arc-job-metrics.sh"
	manifestPath = "k8s/bases/infrastructure/ksail-analysis-runners/config-map-job-metrics.yaml"
)

func generate(script []byte) ([]byte, error) {
	if len(script) == 0 || len(script) > 64*1024 {
		return nil, fmt.Errorf("metrics hook must contain 1–65536 bytes")
	}
	sum := sha256.Sum256(script)
	manifest := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata": map[string]any{
			"name":        fmt.Sprintf("ksail-arc-job-metrics-%x", sum[:5]),
			"namespace":   "arc-ksail-analysis",
			"labels":      map[string]string{"app.kubernetes.io/name": "ksail-arc-job-metrics"},
			"annotations": map[string]string{"kustomize.toolkit.fluxcd.io/substitute": "disabled"},
		},
		"immutable": true,
		"data":      map[string]string{"job-metrics.sh": string(script)},
	}
	data, err := yaml.Marshal(manifest)
	if err != nil {
		return nil, err
	}
	return append([]byte("# Generated by go run ./scripts/generate-ksail-arc-job-metrics -write; do not edit.\n"), data...), nil
}

func run() error {
	write := flag.Bool("write", false, "update the generated manifest")
	flag.Parse()
	if flag.NArg() != 0 {
		return fmt.Errorf("unexpected positional arguments")
	}
	script, err := os.ReadFile(scriptPath)
	if err != nil {
		return err
	}
	data, err := generate(script)
	if err != nil {
		return err
	}
	if *write {
		return os.WriteFile(manifestPath, data, 0644)
	}
	_, err = os.Stdout.Write(data)
	return err
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
