---
apiVersion: v1
kind: Namespace
metadata:
  name: userns-longhorn-smoke
  labels:
    app.kubernetes.io/managed-by: ksail
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.devantler.tech/user-namespaces: enabled
