# Placeholder: populate after first `bao operator init`, then re-encrypt.
# Run: bao operator init -key-shares=3 -key-threshold=2
# Copy the unseal keys and root token here, then: sops -e -i <this-file>
apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal
    namespace: openbao
stringData:
    unseal-key-1: ENC[AES256_GCM,data:RNHRgtb27anOuJTuN78jD3wb,iv:0sZY+j1V/To8w+TtFgZdzFYKe+DcdXnRcyKyqdMWXtw=,tag:gFxeP8DiE0ugkC3DaYms+Q==,type:str]
    unseal-key-2: ENC[AES256_GCM,data:2EHo2s/wUCkRt0jZo44HqiuQ,iv:NWgsWEKkLc63UUWgWAEdKleEDzV02sCPhMQWNZxk2BQ=,tag:C7CJI2ykMxZyhOp4RYEQxQ==,type:str]
    unseal-key-3: ENC[AES256_GCM,data:aTlRAQtzFlM2cWAYeYsLCk07,iv:NM5A7QRbx1NNqhpFfKlxR2x+VNshIkRk8GTKY6AQaOo=,tag:iCfKcu20ZdOWtdZgj0YVhw==,type:str]
    root-token: ENC[AES256_GCM,data:3nqC1YZUh7D46R7PwpbihoiQ,iv:7nQb4fHdKgwpowgdr0hoL50PU0iYknukKzkyGSrVpek=,tag:nyHpe+FARO5aFkj5vb71Og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQlF6ak50Y2ZqWllEaTBW
            QW9sOHVGQjYxQ2ZmcXJ3VVV0dmtCOWFZeDNFCnQzVnpEcFlxY3F1YTN1cVh2UVMr
            U3dMTkVvaFdzbXRFMWFyTnNYOEovREkKLS0tIHdJL0R1WW9VLy9va05KL3lDZGcv
            OE10K1ZaeWpvcDZrY3hoY3U5bjhIS3MKqgq0SYq71EP9h46SI/6m7lOCyP38EDNL
            DWvaGSbsktcBMNIK+7RZuBFj9CtjyQPxMh6Gd9chAaF4zxFOMACWWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:57:10Z"
    mac: ENC[AES256_GCM,data:1eMs9TezN8XKX4dZLdxzRK0p8MaFoWEQsyYpES/d+SGsvPWHdATT1hO5VKQdls9ukBHlxNWri/XJzbUVGms6w7yLbxqI7M+056Mf3MzynBU1B9mDsKXU4l6t/rWkYLE0Fuzup5ltzk4J75DZ00bcmKuCL6pDIki5ENJImjAwMAE=,iv:+zF6r/w2m3NCsfESejyBEPpTUJn/g4pEOPHhyo9DeNw=,tag:MyR/7XR7aq6VGMkjKIvgSA==,type:str]
    version: 3.13.0
