apiVersion: v1
kind: Secret
metadata:
    name: variables-cluster
    namespace: flux-system
stringData:
    cloudflared_tunnel_secret: ENC[AES256_GCM,data:U7cNhEMbJ1eTbTevcbvq/y4vaUcPfseAVIev55k9H4pg2LgsLL8z7ST/ItI=,iv:DxcCKT51pLOZktzPXsc32CDEPpjMDIClVaf1FAYIM9w=,tag:4mcn2ys4Ccbcf8hKWMl7DA==,type:str]
    dex_client_secret: ENC[AES256_GCM,data:jUnfUyW6LZBY5f3nZ4Y5YWAjvu0=,iv:NcQLre+LOgKtd5gz/tf6FpCL5amZ/gQddvL6/uPty70=,tag:TmHMgMuYkFRWsq5Rojq5BA==,type:str]
    github_app_client_secret: ENC[AES256_GCM,data:XC7fgGMEYTTtvypdZxIq8CULw3SWkS5t7kGs7jH3gzabZYnWQG9pWw==,iv:ezpPmqh9v53aj5NrqjyEoX2bQww5Mp2f2UVeCUBtF9g=,tag:6CAfQGtgQmPArYBBpU1Hzw==,type:str]
    hcloud_token: ENC[AES256_GCM,data:xYekiMOjhaxq/dyvslvXZKc8o3Jsp+m1ZgUyOVWBu4kFxGFtr61M7uPHfSd2axHdAiYud9ow3PdoCkF9gJyi4g==,iv:iO+iRnPi2dSgZOrWIPina3COpH0juVkuwAMYnVCvlr0=,tag:lr/7B77Ww1+qVDUK+Dz2gw==,type:str]
    oauth2_proxy_cookie_secret: ENC[AES256_GCM,data:SHzKBurGHhzyaknPyzEy8UO1bDM9PYaCZTMi4vfhjp64Tz8KHyxQwiE5PNg=,iv:Z3KJ+tg7zAPLeJtTTmb0Bwd1wixzBQkFr/rlcMX1bw4=,tag:O6akeH2vZn9rH7kOUv4Eiw==,type:str]
    flux_web_client_secret: ENC[AES256_GCM,data:HG439eFsbyoURdS9ujcmxoRM1iyWr9S+GSMa4WWHahg=,iv:O7IXV1mvRPUL4XnVLsOcmq5DDprAFv+Shxxyf120jT4=,tag:7PbMQmnENjwOqPVXgmnTZg==,type:str]
sops:
    age:
        - recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQjhVYXcvdWthVDhEN3dB
            Mm53UktsdHZYckNlTjRuVjdEa3dwN1B6cDJzClI0UU5uYlphRDhLdGVVMTdGVHRL
            TDRBVGNIYnpqSjJHYTNwZzZHZEM0OGsKLS0tIE9VVmZZWUtwQnBKSXA1VGVrUDAy
            RU02VGc0L1VxTThKK2ZEaDVMSGQ2cUUK2uCzHaosnnfRtgtFQrb5svaHNstLQZKV
            znAhCwrhlhGCuCCewEbyVB60FMMUIT1zhZMLmzIKbCTCn/wVlz5+yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T15:50:32Z"
    mac: ENC[AES256_GCM,data:XmTW6zVaSm0Bu4beNFvP42tia71CZMOI0UypasS0cSywdM7oHjF6IeU//WaQZxgflS2+P1aClZYQ8I0mqW1U3WrelLQY6jU8mmGilwJdOUT0TCOS99WNS/oqQ2rhjw6LnsdnLQZpLIK1MMx5m8gqIOG5EMuijhtTGNiHawcWJ1g=,iv:idcb17vEe6MAotnTWOmPtpfW5b+4ogv2hHhK9+NEKEw=,tag:U9A+NxqUlF5sioSxON5IEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
