apiVersion: v1
kind: Secret
metadata:
    name: variables-cluster
    namespace: flux-system
stringData:
    cloudflared_tunnel_token: ENC[AES256_GCM,data:LegJqH1JuyPpNYO3L1/dMLRdBrNfkxE0/OYeRhjIrKaBPByKYVpSA3h6XK4AcFHxDLZhHiBpNVi73kFcywXZF12uhaP4oYhFhBuYuYMHaO8PVRZ8HG9cYPvwb9zLs+SRv76oZw2M1+PsIYQU3dncJQmly3MgdGd/Y1rCQG50PI77qUzUgEYCMQIcHNnfhBwugYTj0xTagAtCiipk5Jxq6+E65Dsyig4asceFyx9KP1ZOm8/junMimQ==,iv:sn/VOIjDBgo8/XmU9VudlOrWPKYklxQksa3h7sZ7ego=,tag:pP8vf6V78jx8h10aFVQzoQ==,type:str]
    dex_client_secret: ENC[AES256_GCM,data:YONU7rnys4Xqgc8sm1OPuiw7j80=,iv:y2RCcxrpLf8hmaAHIbpOGOpx/oo5fHDabuR688CGqfI=,tag:4HyZVcSK2M+UbB/A139Mow==,type:str]
    github_app_client_secret: ENC[AES256_GCM,data:1d/Bo7NOtvtkc/LK9XK65sDtMD59Grs6m0DxB8MV2t6rgrO7WiZKTg==,iv:c6WWtVIihW8D0UbiWPNaIvRlSuaqRaN86qdgSWioJoU=,tag:0seA3w+LoBrEsylCfRKRFQ==,type:str]
    hcloud_token: ENC[AES256_GCM,data:SZAr2DAW2MLjapBrc85X8siV14RkC+FKsnv4MeK4Keoz/4Tx5WFBwkYT0tdphFWLFUMt74QvVHREsXSOZYqO0A==,iv:ON0fVY3BOszjxkq2HHY7fjJ/sL2bQeogu1hlJqsCLdQ=,tag:kVVD/lNfpO4E37kqkWnT+A==,type:str]
    oauth2_proxy_cookie_secret: ENC[AES256_GCM,data:qYWFl9U4nV/lU8cam5FZXryJm4v6gKjF2Xr+HLKmMoWPDlM5X//+cUui9FI=,iv:UkzMbB4Y9gkMUwP/ImGDAesIuqwJagiH43vcVXbfV1w=,tag:XCSERX2Dd3R10mRtmHou4g==,type:str]
    flux_web_client_secret: ENC[AES256_GCM,data:RHkd062E9SUgp6+8AtZ7SoUxbn/zzf4PGrn9EXhvLIQ=,iv:DB+F2Nbhu25RGkZ10myxxT8Qv4mUmRB57avikslvF4A=,tag:IUiAW4xHJwdH85GP9YkEtg==,type:str]
sops:
    age:
        - recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N1VmOVpjZWhGZms4b1I5
            VmdnTlNjdlc0MWZZMjNFeTg0SUZuQStFREI0CjVjNUpjK1lDWEZYM3o4eGNnU2gv
            QXF2OXVNZ0N5OVlBVVJYa3lORjc3SEEKLS0tIFBBMTlOUW9lVlBwV0V5ejZHUy9H
            SnNOZGs3TnJlV3A1eUgvRlB1djROSU0KKdKq1BI7aysWD8C7Tr69Ic0q5GLGbHi1
            am3X2MaCmenM+MYLmm1gbtEhs3EWMjL1jGwc92dMqVfOHzSgjdbRlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T17:08:48Z"
    mac: ENC[AES256_GCM,data:ApDsuCNMML3wuCkQxQ337JXOCt4ubbJMg66ZniIZ9g73DedKzlRXeBs/omNuX7Q8JaA5mc5FDNTCra7MOsLgCJlfYHaOxNdCvjNkCmb0nwgT1rGQqUTSAu3aQae2bfe08YzdWZ+tJTs5NkmenZOGoBnHotQMKXA8ucIz4EMyhAA=,iv:8hOl61kHu+wcGNuzqnZrmpK5swGrdP7JRAX/S0XaAE4=,tag:8KOnjOV2dYjHhwqOqhSMSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
