package main

import (
	"bytes"
	"errors"
	"fmt"
	"slices"
	"strings"
	"testing"
)

// postureTheme and cveTheme are the two shapes the reconciler sees.
func postureTheme(key string, components ...string) theme {
	return theme{
		Kind:       string(surfacePosture),
		Key:        key,
		Severity:   "High",
		Components: components,
		Count:      len(components),
	}
}

func cveTheme(key string, total int, components ...string) theme {
	return theme{
		Kind:       string(surfaceCVE),
		Key:        key,
		Severity:   key,
		Components: components,
		Count:      len(components),
		Total:      total,
	}
}

// goldenPostureBody is the EXACT body a previous run wrote for
// postureTheme("C-0016", "apps/Deployment/web").
//
// It is a literal rather than a renderBody() call, and that is the whole point.
// The zero-write property below asserts that an unchanged theme renders
// identically to what is already filed; if the existing body were produced by
// calling renderBody in the test, the comparison would hold for ANY renderBody
// — including one that embedded a timestamp, which is precisely the instability
// that would turn every run into an update. Pinning the bytes here means a
// format drift fails this test instead of silently churning the backlog.
const goldenPostureBody = "> 🤖 Generated by the Agentic Engineer\n\n" +
	"<!-- kubescape-backlog-bridge:fingerprint=" + goldenPostureFingerprint + " -->\n\n" +
	"Filed automatically from live Kubescape findings by " +
	"`scripts/kubescape-backlog-bridge`. Part of #2854.\n\n" +
	"**Surface:** posture\n" +
	"**Severity:** High\n" +
	"\n**Affected components (1):**\n\n" +
	"- `apps/Deployment/web`\n" +
	"\nThis issue is reconciled automatically: it is updated when the affected set " +
	"changes and closed when the finding is gone. Edit the title or body only if you are " +
	"willing to have it overwritten — the fingerprint comment above is what identifies it.\n"

// goldenPostureFingerprint pins sha256("posture|C-0016")[:16], computed
// independently of this package: `printf 'posture|C-0016' | shasum -a 256`.
const goldenPostureFingerprint = "43379dbb9d5d9566"

const goldenPostureTitle = "security(posture): C-0016 fails"

func TestRenderMatchesGolden(t *testing.T) {
	th := postureTheme("C-0016", "apps/Deployment/web")

	if got := th.Fingerprint(); got != goldenPostureFingerprint {
		t.Fatalf("fingerprint drifted: got %q want %q", got, goldenPostureFingerprint)
	}

	if got := renderTitle(th); got != goldenPostureTitle {
		t.Errorf("title drifted:\n got %q\nwant %q", got, goldenPostureTitle)
	}

	if got := renderBody(th); got != goldenPostureBody {
		t.Errorf("body drifted:\n got %q\nwant %q", got, goldenPostureBody)
	}
}

// TestRenderIsDeterministic guards the anti-churn guarantee at its source: two
// renders of one theme must be byte-identical, so an unchanged cluster writes
// nothing. A component set is deliberately supplied in a different ORDER each
// time, because the reconciler compares rendered text and any order-sensitivity
// here would surface as a permanent update loop rather than as a failure.
func TestRenderIsDeterministic(t *testing.T) {
	a := renderBody(postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg"))
	b := renderBody(postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg"))

	if a != b {
		t.Fatalf("renderBody is not deterministic:\n%q\n%q", a, b)
	}
}

func trackedPosture(number int, open bool) backlogEntry {
	return backlogEntry{Number: number, Title: goldenPostureTitle, Body: goldenPostureBody, Open: open}
}

// TestUnchangedStateProducesNoWrites is the acceptance criterion "no issue
// spam: unchanged cluster state produces zero writes", asserted as a property.
func TestUnchangedStateProducesNoWrites(t *testing.T) {
	themes := []theme{postureTheme("C-0016", "apps/Deployment/web")}
	existing := []backlogEntry{trackedPosture(41, true)}

	p, err := planWrites(themes, existing, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("unchanged state planned %d write(s): %+v", len(p.Actions), p.Actions)
	}

	// CONTROL — the assertion above must be capable of failing. One byte of
	// drift in the tracked body has to produce an update; if it does not, the
	// comparison is vacuous and the empty plan above proved nothing.
	drifted := []backlogEntry{{
		Number: 41,
		Title:  goldenPostureTitle,
		Body:   strings.Replace(goldenPostureBody, "apps/Deployment/web", "apps/Deployment/api", 1),
		Open:   true,
	}}

	if drifted[0].Body == goldenPostureBody {
		t.Fatal("control is inert: the substitution did not change the body")
	}

	ctrl, err := planWrites(themes, drifted, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "update" {
		t.Fatalf("control did not flip: want one update, got %+v", ctrl.Actions)
	}
}

func TestUntrackedThemeIsCreated(t *testing.T) {
	p, err := planWrites([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		nil, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "create" {
		t.Fatalf("want one create, got %+v", p.Actions)
	}

	if p.Actions[0].Number != 0 {
		t.Errorf("a create must carry no issue number, got #%d", p.Actions[0].Number)
	}
}

// TestReturningThemeReopensRatherThanRecreates pins the property that keeps
// "at most one open issue per theme" true across a resolve/regress cycle.
func TestReturningThemeReopensRatherThanRecreates(t *testing.T) {
	p, err := planWrites([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]backlogEntry{trackedPosture(41, false)}, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "reopen" || p.Actions[0].Number != 41 {
		t.Fatalf("want one reopen of #41, got %+v", p.Actions)
	}
}

// TestAffectedSetChangeUpdatesTheSameIssue proves a workload joining a theme
// lands on the ORIGINAL issue. The fingerprint excludes the component set
// precisely so this is an update; were it included, this would be a create and
// the old issue would be stranded.
func TestAffectedSetChangeUpdatesTheSameIssue(t *testing.T) {
	grown := postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg")

	p, err := planWrites([]theme{grown},
		[]backlogEntry{trackedPosture(41, true)}, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "update" || p.Actions[0].Number != 41 {
		t.Fatalf("want one update of #41, got %+v", p.Actions)
	}

	if !strings.Contains(p.Actions[0].Body, "db/StatefulSet/pg") {
		t.Error("the update body does not carry the newly affected component")
	}
}

// TestCloseRequiresInputsComplete is the destructive half's gate. A run that
// cannot assert it examined every object must never mark a finding resolved.
func TestCloseRequiresInputsComplete(t *testing.T) {
	existing := []backlogEntry{trackedPosture(41, true)}

	p, err := planWrites(nil, existing, []surface{surfacePosture}, false, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("a partial run planned writes: %+v", p.Actions)
	}

	// CONTROL — with the assertion supplied, and nothing else changed, the same
	// input must close. Without this the test above would pass for a planner
	// that never closes at all.
	ctrl, err := planWrites(nil, existing, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "close" || ctrl.Actions[0].Number != 41 {
		t.Fatalf("control did not flip: want one close of #41, got %+v", ctrl.Actions)
	}
}

// TestCloseIsScopedToExaminedSurfaces stops a posture-only sweep from resolving
// every CVE finding it never looked at.
func TestCloseIsScopedToExaminedSurfaces(t *testing.T) {
	cve := cveTheme("Critical", 3, "apps/Deployment/web")
	cveEntry := backlogEntry{
		Number: 77,
		Title:  renderTitle(cve),
		Body:   renderBody(cve),
		Open:   true,
	}

	p, err := planWrites(nil, []backlogEntry{cveEntry}, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("a posture-only run planned CVE writes: %+v", p.Actions)
	}

	// CONTROL — the same entry, with its own surface examined, must close.
	ctrl, err := planWrites(nil, []backlogEntry{cveEntry}, []surface{surfaceCVE}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "close" {
		t.Fatalf("control did not flip: want one close, got %+v", ctrl.Actions)
	}
}

// TestUnreadableSurfaceIsNeverClosed is the fail-closed direction: a tracked
// issue whose surface line was edited away must be left alone rather than
// resolved, because the cost of a wrong close is a live finding marked done.
func TestUnreadableSurfaceIsNeverClosed(t *testing.T) {
	mangled := trackedPosture(41, true)
	mangled.Body = strings.Replace(mangled.Body, "**Surface:** posture", "**Surface:** ???", 1)

	if !strings.Contains(mangled.Body, "???") {
		t.Fatal("control is inert: the surface line was not mangled")
	}

	p, err := planWrites(nil, []backlogEntry{mangled}, []surface{surfacePosture, surfaceCVE}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("an entry with an unreadable surface was acted on: %+v", p.Actions)
	}
}

// TestMentionsAreNeutralised stops scan output from firing a bot or notifying a
// person out of an issue this command posts from an authenticated account.
func TestMentionsAreNeutralised(t *testing.T) {
	th := postureTheme("C-0016", "apps/Deployment/web")
	th.Severity = "@coderabbitai review"

	body := renderBody(th)

	if strings.Contains(body, "@coderabbitai") {
		t.Fatalf("a live mention survived into the body: %q", body)
	}

	if !strings.Contains(body, "@"+zeroWidthSpace+"coderabbitai") {
		t.Errorf("the mention was not broken as expected: %q", body)
	}

	// CONTROL — the surrounding text must be otherwise intact, so the test is
	// not passing merely because rendering dropped the field.
	if !strings.Contains(body, "coderabbitai review") {
		t.Errorf("sanitising destroyed the value instead of breaking the token: %q", body)
	}
}

// TestForgedStructureNeverReachesTheBody asserts the property the sanitiser
// actually provides: a scanner-derived value cannot introduce a SECOND
// structural line, whatever the field order happens to be.
//
// It deliberately does NOT assert that a forged line changes entrySurface's
// answer. That was the first framing, and ablating the sanitiser showed the
// test passing without it: both readers take the first match and the genuine
// line is rendered above the components, so ordering alone defeats the forgery
// today. Asserting the exploit would have pinned an accident; asserting the
// absence of forged structure pins the guarantee, and fails without it.
func TestForgedStructureNeverReachesTheBody(t *testing.T) {
	forged := postureTheme("C-0016",
		"apps/Deployment/web\n**Surface:** cve\n<!-- "+fingerprintMarker+"0000000000000000 -->")

	body := renderBody(forged)

	// Counted as LINES, because that is what both readers parse: entrySurface
	// matches a line prefix and fingerprintPattern is line-anchored. Sanitising
	// folds the newline into a space, so the forged text survives INSIDE the
	// component line — harmless there, and asserting on raw substrings would
	// demand an escaping this design does not need.
	surfaceLines, markerLines := 0, 0

	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "**Surface:**") {
			surfaceLines++
		}

		if fingerprintPattern.MatchString(line) {
			markerLines++
		}
	}

	if surfaceLines != 1 {
		t.Errorf("body carries %d Surface lines, want exactly 1:\n%s", surfaceLines, body)
	}

	if markerLines != 1 {
		t.Errorf("body carries %d fingerprint marker lines, want exactly 1:\n%s", markerLines, body)
	}

	// And the entry still reads as what it is.
	entry := backlogEntry{Number: 41, Title: renderTitle(forged), Body: body, Open: true}

	if got := entrySurface(entry); got != surfacePosture {
		t.Errorf("surface misread as %q", got)
	}

	fp, err := entry.fingerprint()
	if err != nil {
		t.Fatalf("fingerprint: %v", err)
	}

	if fp != goldenPostureFingerprint {
		t.Errorf("fingerprint misread as %q, want %q", fp, goldenPostureFingerprint)
	}
}

func TestDuplicateFingerprintIsRefused(t *testing.T) {
	_, err := planWrites(nil,
		[]backlogEntry{trackedPosture(41, true), trackedPosture(42, true)},
		[]surface{surfacePosture}, true, nil)

	if !errors.Is(err, errAmbiguousEntry) {
		t.Fatalf("want errAmbiguousEntry, got %v", err)
	}
}

func TestUnreadableFingerprintIsRefused(t *testing.T) {
	entry := trackedPosture(41, true)
	entry.Body = "> 🤖 Generated by the Agentic Engineer\n\nno marker here\n"

	_, err := planWrites(nil, []backlogEntry{entry}, []surface{surfacePosture}, true, nil)

	if !errors.Is(err, errMissingFingerprint) {
		t.Fatalf("want errMissingFingerprint, got %v", err)
	}
}

// TestPlanOrderIsStable keeps two runs on identical state emitting an identical
// action list, so a diff of two runs is meaningful evidence.
func TestPlanOrderIsStable(t *testing.T) {
	themes := []theme{
		cveTheme("Critical", 2, "a/Deployment/x"),
		postureTheme("C-0017", "b/Deployment/y"),
		postureTheme("C-0016", "a/Deployment/x"),
	}

	first, err := planWrites(themes, nil, []surface{surfacePosture, surfaceCVE}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	shuffled := []theme{themes[2], themes[0], themes[1]}

	second, err := planWrites(shuffled, nil, []surface{surfacePosture, surfaceCVE}, true, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(first.Actions) != 3 {
		t.Fatalf("want 3 creates, got %+v", first.Actions)
	}

	for i := range first.Actions {
		if first.Actions[i].Title != second.Actions[i].Title {
			t.Fatalf("action order depends on input order at %d: %q vs %q",
				i, first.Actions[i].Title, second.Actions[i].Title)
		}
	}
}

// fakeStore records every call so a test can assert on writes that did NOT
// happen — the property an inspected plan cannot prove.
type fakeStore struct {
	entries []backlogEntry
	calls   []string
	nextNum int
	failOn  string
}

func (f *fakeStore) list() ([]backlogEntry, error) {
	if f.failOn == "list" {
		return nil, errors.New("boom")
	}

	return f.entries, nil
}

func (f *fakeStore) create(title, _ string) (int, error) {
	if f.failOn == "create" {
		return 0, errors.New("boom")
	}

	f.nextNum++
	f.calls = append(f.calls, "create:"+title)

	return f.nextNum, nil
}

// update, reopen and close all honour failOn, not just list and create.
//
// applyPlan wraps each of these on the same stop-at-first-failure path, so a
// regression that swallowed the error from any ONE of them would leave a
// create-only fake green. close is the destructive branch, which makes it the
// one that most needs to be reachable by the failure test.
func (f *fakeStore) update(number int, _, _ string) error {
	if f.failOn == "update" {
		return errors.New("boom")
	}

	f.calls = append(f.calls, fmt.Sprintf("update:%d", number))

	return nil
}

func (f *fakeStore) reopen(number int, _, _ string) error {
	if f.failOn == "reopen" {
		return errors.New("boom")
	}

	f.calls = append(f.calls, fmt.Sprintf("reopen:%d", number))

	return nil
}

func (f *fakeStore) close(number int, _, reason string) error {
	if f.failOn == "close" {
		return errors.New("boom")
	}

	f.calls = append(f.calls, fmt.Sprintf("close:%d:%s", number, reason))

	return nil
}

// TestReconcileWritesNothingOnUnchangedState closes the loop end-to-end: not
// merely an empty plan, but a driver that issues no mutating call at all.
func TestReconcileWritesNothingOnUnchangedState(t *testing.T) {
	store := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	var out bytes.Buffer

	err := reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]surface{surfacePosture}, true, nil, store, &out)
	if err != nil {
		t.Fatalf("reconcile: %v", err)
	}

	if len(store.calls) != 0 {
		t.Fatalf("unchanged state issued writes: %v", store.calls)
	}

	if !strings.Contains(out.String(), "no changes") {
		t.Errorf("run said nothing about doing nothing: %q", out.String())
	}

	// CONTROL — a changed theme through the SAME path must write, so the
	// silence above is a decision and not a broken driver.
	ctrlStore := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	err = reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg")},
		[]surface{surfacePosture}, true, nil, ctrlStore, &bytes.Buffer{})
	if err != nil {
		t.Fatalf("control reconcile: %v", err)
	}

	if len(ctrlStore.calls) != 1 || ctrlStore.calls[0] != "update:41" {
		t.Fatalf("control did not flip: want [update:41], got %v", ctrlStore.calls)
	}
}

// TestWithheldCloseIsDisclosed pins the honesty property found while exercising
// the real binary: a gated run declined to close a stale entry and reported
// only "no changes", which reads as a reconciled backlog. A withheld action and
// a completed one must not render identically.
func TestWithheldCloseIsDisclosed(t *testing.T) {
	store := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	var out bytes.Buffer

	// No themes: the finding is gone. No -inputs-complete: closing is gated.
	if err := reconcile(nil, []surface{surfacePosture}, false, nil, store, &out); err != nil {
		t.Fatalf("reconcile: %v", err)
	}

	if len(store.calls) != 0 {
		t.Fatalf("a gated run wrote: %v", store.calls)
	}

	if !strings.Contains(out.String(), "left OPEN") {
		t.Errorf("the withheld close was not disclosed: %q", out.String())
	}

	// CONTROL — a run with nothing withheld must NOT emit the note, or the
	// disclosure is unconditional boilerplate rather than a signal.
	var ctrl bytes.Buffer

	ctrlStore := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}
	if err := reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]surface{surfacePosture}, false, nil, ctrlStore, &ctrl); err != nil {
		t.Fatalf("control reconcile: %v", err)
	}

	if strings.Contains(ctrl.String(), "left OPEN") {
		t.Errorf("the note fired with nothing withheld: %q", ctrl.String())
	}
}

// TestReconcileStopsAtFirstFailure covers EVERY mutating branch, not just
// create. applyPlan wraps all four on the same path, so a regression that
// swallowed the error from update, reopen or close would have left a
// create-only test green — and close is the destructive one.
func TestReconcileStopsAtFirstFailure(t *testing.T) {
	cases := []struct {
		name           string
		failOn         string
		themes         []theme
		existing       []backlogEntry
		inputsComplete bool
	}{
		{
			name:           "create",
			failOn:         "create",
			themes:         []theme{postureTheme("C-0016", "apps/Deployment/web")},
			inputsComplete: true,
		},
		{
			name:           "update",
			failOn:         "update",
			themes:         []theme{postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg")},
			existing:       []backlogEntry{trackedPosture(41, true)},
			inputsComplete: true,
		},
		{
			name:           "reopen",
			failOn:         "reopen",
			themes:         []theme{postureTheme("C-0016", "apps/Deployment/web")},
			existing:       []backlogEntry{trackedPosture(41, false)},
			inputsComplete: true,
		},
		{
			// The destructive branch: a tracked issue with no matching finding,
			// on a run that has asserted complete input.
			name:           "close",
			failOn:         "close",
			themes:         nil,
			existing:       []backlogEntry{trackedPosture(41, true)},
			inputsComplete: true,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			store := &fakeStore{failOn: c.failOn, entries: c.existing}

			err := reconcile(c.themes, []surface{surfacePosture},
				c.inputsComplete, nil, store, &bytes.Buffer{})

			if !errors.Is(err, errWriteFailed) {
				t.Fatalf("want errWriteFailed, got %v", err)
			}

			// CONTROL — the SAME invocation with a healthy store must succeed
			// AND must actually perform the branch under test. Without this the
			// assertion above would pass for a case that never reached it, which
			// is how a failOn the fake ignores looks identical to one it honours.
			ctrl := &fakeStore{entries: c.existing}
			if err := reconcile(c.themes, []surface{surfacePosture},
				c.inputsComplete, nil, ctrl, &bytes.Buffer{}); err != nil {
				t.Fatalf("control reconcile failed: %v", err)
			}

			var performed bool

			for _, call := range ctrl.calls {
				if strings.HasPrefix(call, c.failOn+":") {
					performed = true
				}
			}

			if !performed {
				t.Fatalf("control never performed a %q; calls=%v", c.failOn, ctrl.calls)
			}
		})
	}
}

func TestParseIssueNumber(t *testing.T) {
	n, err := parseIssueNumber("https://github.com/devantler-tech/platform/issues/2899\n")
	if err != nil {
		t.Fatalf("parseIssueNumber: %v", err)
	}

	if n != 2899 {
		t.Errorf("got #%d want #2899", n)
	}

	if _, err := parseIssueNumber("Creating issue in devantler-tech/platform\n"); err == nil {
		t.Error("want an error when no issue URL is present")
	}
}

// TestListRefusesTruncatedPage pins the duplicate-storm guard: a listing that
// reaches the CLI's own ceiling cannot be distinguished from a complete one, so
// it is refused rather than reconciled against.
func TestListRefusesTruncatedPage(t *testing.T) {
	var page []string
	for i := range listLimit {
		page = append(page, fmt.Sprintf(`{"number":%d,"title":"t","body":"b","state":"OPEN"}`, i+1))
	}

	store := &ghStore{repo: "o/r", run: func(...string) ([]byte, error) {
		return []byte("[" + strings.Join(page, ",") + "]"), nil
	}}

	if _, err := store.list(); !errors.Is(err, errWriteFailed) {
		t.Fatalf("a full page was accepted as complete: %v", err)
	}

	// CONTROL — one fewer issue is not truncated and must be accepted.
	store.run = func(...string) ([]byte, error) {
		return []byte("[" + strings.Join(page[:listLimit-1], ",") + "]"), nil
	}

	entries, err := store.list()
	if err != nil {
		t.Fatalf("control list: %v", err)
	}

	if len(entries) != listLimit-1 {
		t.Fatalf("control returned %d entries, want %d", len(entries), listLimit-1)
	}
}

// TestListMapsStateToOpen guards the reopen path's input: `gh` emits OPEN/CLOSED
// in upper case, and reading it case-sensitively would mark every tracked issue
// closed and turn every update into a reopen.
func TestListMapsStateToOpen(t *testing.T) {
	store := &ghStore{repo: "o/r", run: func(...string) ([]byte, error) {
		return []byte(`[{"number":1,"title":"a","body":"b","state":"OPEN"},` +
			`{"number":2,"title":"c","body":"d","state":"CLOSED"}]`), nil
	}}

	entries, err := store.list()
	if err != nil {
		t.Fatalf("list: %v", err)
	}

	if !entries[0].Open || entries[1].Open {
		t.Fatalf("state mapping wrong: %+v", entries)
	}
}

// TestPartialInputWithholdsUpdate is the non-destructive half of the same gate
// TestCloseRequiresInputsComplete covers, and it exists because "non-destructive"
// was the wrong word for it. A theme derived from a subset lists only that
// subset's components, so writing it over a tracked entry DELETES the components
// this run never examined — recorded scope lost while the findings are still
// live, which reads to a human exactly like remediation.
func TestPartialInputWithholdsUpdate(t *testing.T) {
	// Deliberately SHRINKING: the tracked entry names one component and this
	// derivation names a different one, so the rendered bodies differ and the
	// byte-comparison short circuit cannot be what withholds the write.
	subset := postureTheme("C-0016", "db/StatefulSet/pg")
	existing := []backlogEntry{trackedPosture(41, true)}

	p, err := planWrites([]theme{subset}, existing, []surface{surfacePosture}, false, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("a partial run planned writes: %+v", p.Actions)
	}

	if p.WithheldUpdates != 1 {
		t.Errorf("want 1 withheld update disclosed, got %d", p.WithheldUpdates)
	}

	// CONTROL — the same input with the completeness assertion must update.
	// Without it this test would pass for a planner that never updates at all.
	ctrl, err := planWrites([]theme{subset}, existing, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "update" || ctrl.Actions[0].Number != 41 {
		t.Fatalf("control did not flip: want one update of #41, got %+v", ctrl.Actions)
	}

	if ctrl.WithheldUpdates != 0 {
		t.Errorf("control must withhold nothing, got %d", ctrl.WithheldUpdates)
	}
}

// TestUnchangedThemeUnderPartialInputWithholdsNothing pins the ordering of the
// gate against the byte comparison. A subset run whose theme happens to match
// what is already filed has nothing to write in either mode, and counting it as
// withheld would report pending work that does not exist — the same
// false-signal failure mode as the reverse, one step over.
func TestUnchangedThemeUnderPartialInputWithholdsNothing(t *testing.T) {
	unchanged := postureTheme("C-0016", "apps/Deployment/web")

	p, err := planWrites([]theme{unchanged},
		[]backlogEntry{trackedPosture(41, true)}, []surface{surfacePosture}, false, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() || p.WithheldUpdates != 0 {
		t.Fatalf("want a silent no-op, got %+v withheld=%d", p.Actions, p.WithheldUpdates)
	}
}

// TestPartialInputReopenKeepsFiledScope covers the one write a partial run must
// still perform. Leaving a live finding closed is worse than a stale body, so
// the state change happens — but carrying the subset render into it would strip
// the entry back to what this run happened to look at, which is the very loss
// the update gate above exists to prevent.
func TestPartialInputReopenKeepsFiledScope(t *testing.T) {
	subset := postureTheme("C-0016", "db/StatefulSet/pg")
	closed := []backlogEntry{trackedPosture(41, false)}

	p, err := planWrites([]theme{subset}, closed, []surface{surfacePosture}, false, nil)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "reopen" || p.Actions[0].Number != 41 {
		t.Fatalf("want one reopen of #41, got %+v", p.Actions)
	}

	if p.Actions[0].Body != goldenPostureBody || p.Actions[0].Title != goldenPostureTitle {
		t.Errorf("a partial reopen rewrote the filed text:\n%q", p.Actions[0].Body)
	}

	// CONTROL — with completeness asserted the reopen carries the fresh render,
	// so the assertion above is attributable to the gate and not to a reopen
	// that never rewrites anything.
	ctrl, err := planWrites([]theme{subset}, closed, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || !strings.Contains(ctrl.Actions[0].Body, "db/StatefulSet/pg") {
		t.Fatalf("control did not flip: want the fresh render, got %+v", ctrl.Actions)
	}
}

// TestAcceptedThemeClosesAsAcceptedNotAsGone separates the two ways a theme
// leaves a derivation. Both arrive here as "absent from themes", but one means
// the finding is gone and the other means a declared exception covers every
// occurrence of a finding that is STILL FAILING. Closing the second as "no
// longer present" writes the wrong fact into the issue's permanent timeline,
// exactly when a reader needs to know the exception is load-bearing.
func TestAcceptedThemeClosesAsAcceptedNotAsGone(t *testing.T) {
	existing := []backlogEntry{trackedPosture(41, true)}
	accepted := map[string]struct{}{goldenPostureFingerprint: {}}

	p, err := planWrites(nil, existing, []surface{surfacePosture}, true, accepted)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "close" {
		t.Fatalf("want one close of #41, got %+v", p.Actions)
	}

	if p.Actions[0].Reason != acceptedComment {
		t.Errorf("an accepted finding closed as gone:\n%q", p.Actions[0].Reason)
	}

	// CONTROL — the same close with no acceptance recorded must carry the
	// gone wording, so the assertion above is attributable to the accepted set
	// and not to a planner that always says "accepted".
	ctrl, err := planWrites(nil, existing, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Reason != closeComment {
		t.Fatalf("control did not flip: want the gone wording, got %+v", ctrl.Actions)
	}
}

// TestWithheldUpdateIsDisclosed keeps a gated run from rendering as a clean one.
// A run that declined to update has not reconciled the backlog, and printing
// only "no changes" reports that as a matching state — this command's own core
// failure mode turned inward on its output.
func TestWithheldUpdateIsDisclosed(t *testing.T) {
	store := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	var out bytes.Buffer

	if err := reconcile([]theme{postureTheme("C-0016", "db/StatefulSet/pg")},
		[]surface{surfacePosture}, false, nil, store, &out); err != nil {
		t.Fatalf("reconcile: %v", err)
	}

	if !strings.Contains(out.String(), "left UNCHANGED") {
		t.Errorf("a withheld update was not disclosed, got %q", out.String())
	}

	if len(store.calls) != 0 {
		t.Errorf("a partial run issued %v", store.calls)
	}
}

// TestAcceptedCloseCarriesTheNotPlannedDisposition keeps the structured state
// GitHub renders in step with the comment posted beside it. A finding closed
// because an exception covers it is still failing; recording it as "completed"
// tells every board filter the opposite of what the close comment says.
func TestAcceptedCloseCarriesTheNotPlannedDisposition(t *testing.T) {
	existing := []backlogEntry{trackedPosture(41, true)}

	p, err := planWrites(nil, existing, []surface{surfacePosture}, true,
		map[string]struct{}{goldenPostureFingerprint: {}})
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Disposition != dispositionNotPlanned {
		t.Fatalf("want a not-planned close, got %+v", p.Actions)
	}

	// CONTROL — a genuinely gone finding must keep the completed disposition,
	// so the assertion above is attributable to acceptance rather than to a
	// planner that marks every close not-planned.
	ctrl, err := planWrites(nil, existing, []surface{surfacePosture}, true, nil)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Disposition != dispositionCompleted {
		t.Fatalf("control did not flip: got %+v", ctrl.Actions)
	}
}

// TestDispositionReachesTheStore closes the gap between planning a disposition
// and sending one: applyPlan is what actually passes it to `gh`, and a driver
// that dropped the field would leave the plan correct and every close wrong.
func TestDispositionReachesTheStore(t *testing.T) {
	store := &fakeStore{}

	err := applyPlan(plan{Actions: []issueAction{{
		Kind: "close", Number: 41, Reason: acceptedComment, Disposition: dispositionNotPlanned,
	}}}, store, &bytes.Buffer{})
	if err != nil {
		t.Fatalf("applyPlan: %v", err)
	}

	if len(store.calls) != 1 || store.calls[0] != "close:41:not planned" {
		t.Fatalf("the disposition did not reach the store: %v", store.calls)
	}
}

// TestWithheldRunDoesNotClaimTheBacklogMatches stops the summary contradicting
// the note directly above it. A run that reported a tracked issue differs, then
// said every derived theme already matches, reads as synchronized when it is
// deliberately not.
func TestWithheldRunDoesNotClaimTheBacklogMatches(t *testing.T) {
	var out bytes.Buffer

	if err := applyPlan(plan{WithheldUpdates: 1}, &fakeStore{}, &out); err != nil {
		t.Fatalf("applyPlan: %v", err)
	}

	if strings.Contains(out.String(), "already matches") {
		t.Errorf("a withheld run claimed the backlog matches:\n%s", out.String())
	}

	if !strings.Contains(out.String(), "no writes performed") {
		t.Errorf("a withheld run must still say it wrote nothing, got:\n%s", out.String())
	}

	// CONTROL — a genuinely clean run keeps the original wording, so the
	// assertion above is attributable to the withheld count.
	var clean bytes.Buffer
	if err := applyPlan(plan{}, &fakeStore{}, &clean); err != nil {
		t.Fatalf("control applyPlan: %v", err)
	}

	if !strings.Contains(clean.String(), "already matches") {
		t.Fatalf("control did not flip, got:\n%s", clean.String())
	}
}

// TestBodyBoundsTheComponentListButNotTheCount keeps a broadly-failing control
// from rendering a body GitHub refuses. applyPlan stops at the first failure, so
// one oversized issue would block every remaining action in the run — not just
// its own.
func TestBodyBoundsTheComponentListButNotTheCount(t *testing.T) {
	// Sized at the WORST CASE the cluster can produce, not a convenient short
	// name. component.String joins namespace/kind/name, and an RFC 1123 name
	// runs to 253 characters, so a realistic upper bound is a couple of hundred
	// characters per line. With ~35-character names the body came to ~11KB and
	// the githubIssueBodyLimit assertion below could not fail for ANY value of
	// maxListedComponents up to several thousand — it read as a guard while
	// binding nothing.
	const worstCaseNameLen = 180

	components := make([]string, maxListedComponents+25)
	for i := range components {
		stem := fmt.Sprintf("ns-%04d/Deployment/workload-%04d-", i, i)
		components[i] = stem + strings.Repeat("x", worstCaseNameLen-len(stem))
	}

	body := renderBody(postureTheme("C-0016", components...))

	if !strings.Contains(body, fmt.Sprintf("**Affected components (%d):**", len(components))) {
		t.Error("the true component count must survive truncation")
	}

	if got := strings.Count(body, "\n- `"); got != maxListedComponents {
		t.Errorf("listed %d components, want %d", got, maxListedComponents)
	}

	if !strings.Contains(body, "…and 25 more") {
		t.Errorf("the omission is not disclosed:\n%s", body[len(body)-400:])
	}

	if len(body) >= githubIssueBodyLimit {
		t.Errorf("body is %d chars, over GitHub's %d limit", len(body), githubIssueBodyLimit)
	}

	// CONTROL — a theme under the bound must render every component and say
	// nothing about omissions, so the truncation above is attributable to size.
	small := renderBody(postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg"))
	if strings.Count(small, "\n- `") != 2 || strings.Contains(small, "more (") {
		t.Errorf("control did not flip:\n%s", small)
	}
}

// TestTruncatedBodyIsStable protects the anti-churn guarantee across the new
// branch: an unstable truncation would make every run an update.
func TestTruncatedBodyIsStable(t *testing.T) {
	components := make([]string, maxListedComponents+3)
	for i := range components {
		components[i] = fmt.Sprintf("ns-%04d/Deployment/workload-%04d", i, i)
	}

	first := renderBody(postureTheme("C-0016", components...))
	if second := renderBody(postureTheme("C-0016", components...)); first != second {
		t.Error("a truncated body is not byte-stable across renders")
	}
}

// TestFirstCreateProvisionsEveryLabelItApplies covers a failure that only ever
// appears on a repository this command has never run against — which is exactly
// when nobody is watching. `gh issue create --label` associates an existing
// label; it does not create one, so without this the first untracked theme
// fails and applyPlan's stop-at-first-failure blocks the whole run.
//
// The assertion is that the provisioned set EQUALS the applied set, derived from
// createLabels rather than hard-coded. A count-based check ("two calls") passed
// while `security` was applied but never provisioned, because it pinned the
// number of calls instead of the relationship the guarantee is about — so
// adding a label to create silently broke the guarantee and kept the test green.
func TestFirstCreateProvisionsEveryLabelItApplies(t *testing.T) {
	var args [][]string

	store := &ghStore{repo: "o/r", run: func(a ...string) ([]byte, error) {
		args = append(args, a)

		return []byte("https://github.com/o/r/issues/7\n"), nil
	}}

	if _, err := store.create("t", "b"); err != nil {
		t.Fatalf("create: %v", err)
	}

	if len(args) != len(createLabels)+1 {
		t.Fatalf("want one label call per createLabels entry then a create, got %v", args)
	}

	provisioned := map[string]bool{}

	for _, a := range args[:len(createLabels)] {
		if a[0] != "label" || a[1] != "create" {
			t.Fatalf("a label call was expected before the create: %v", a)
		}

		if !slices.Contains(a, "--force") {
			t.Errorf("label provisioning must be idempotent: %v", a)
		}

		provisioned[a[2]] = true
	}

	createCall := args[len(createLabels)]
	if createCall[0] != "issue" || createCall[1] != "create" {
		t.Fatalf("the last call is not the create: %v", createCall)
	}

	// Every label the create APPLIES must have been provisioned above. This is
	// the direction that actually fails a run: an applied-but-unprovisioned
	// label is refused by GitHub.
	for i, a := range createCall {
		if a != "--label" || i+1 >= len(createCall) {
			continue
		}

		if !provisioned[createCall[i+1]] {
			t.Errorf("create applies label %q that was never provisioned", createCall[i+1])
		}
	}

	// And the set is exactly createLabels, so neither side can gain an entry
	// the other does not know about.
	for _, l := range createLabels {
		if !provisioned[l.name] {
			t.Errorf("createLabels entry %q was not provisioned", l.name)
		}

		if !slices.Contains(createCall, l.name) {
			t.Errorf("createLabels entry %q was not applied by create", l.name)
		}
	}

	// A second create must NOT re-ask: one call per run, not one per issue.
	if _, err := store.create("t2", "b2"); err != nil {
		t.Fatalf("second create: %v", err)
	}

	if len(args) != len(createLabels)+2 {
		t.Fatalf("the label check repeated per issue: %v", args)
	}
}

// TestFingerprintSurvivesCRLFBodies covers a body EDITED IN THE GITHUB WEB UI.
// The API returns such a body with CRLF line endings, and Go's (?m)$ matches
// only before \n — so before the pattern tolerated \r, the marker line ended
// "-->\r" and did not match.
//
// The consequence is not a cosmetic miss and not a duplicate: fingerprint
// failure is deliberately fail-closed, so planWrites returns
// errMissingFingerprint and EVERY subsequent run refuses until someone
// hand-repairs the body. One maintainer edit would wedge the bridge for good.
func TestFingerprintSurvivesCRLFBodies(t *testing.T) {
	lf := renderBody(postureTheme("C-0016", "apps/Deployment/web"))

	want, err := (backlogEntry{Number: 1, Body: lf}).fingerprint()
	if err != nil {
		t.Fatalf("the LF body this command writes must parse: %v", err)
	}

	crlf := strings.ReplaceAll(lf, "\n", "\r\n")

	// Guard the fixture itself: if renderBody ever emitted CRLF, the two bodies
	// would be identical and this test would prove nothing.
	if crlf == lf {
		t.Fatal("fixture is inert: the CRLF body is byte-identical to the LF one")
	}

	got, err := (backlogEntry{Number: 1, Body: crlf}).fingerprint()
	if err != nil {
		t.Fatalf("a web-UI-edited (CRLF) body must still parse: %v", err)
	}

	if got != want {
		t.Errorf("CRLF body yielded fingerprint %q, want %q", got, want)
	}

	// CONTROL — a body whose marker is genuinely absent must STILL be refused,
	// so tolerating \r did not turn the fail-closed guard into a permissive one.
	stripped := strings.ReplaceAll(crlf, fingerprintMarker, "not-the-marker=")
	if _, err := (backlogEntry{Number: 1, Body: stripped}).fingerprint(); !errors.Is(err, errMissingFingerprint) {
		t.Errorf("a body with no marker must stay refused, got %v", err)
	}

	// CONTROL — the anchor must still reject a marker that is not on its own
	// line, which is the injection case the anchoring exists for.
	midline := "prefix <!-- " + fingerprintMarker + "0123456789abcdef -->\r\n"
	if _, err := (backlogEntry{Number: 1, Body: midline}).fingerprint(); !errors.Is(err, errMissingFingerprint) {
		t.Errorf("a mid-line marker must not be honoured, got %v", err)
	}
}

// TestTitleIsBoundedForOverlongKeys keeps one scanner-derived key from failing
// the create call and blocking every remaining action in the run — the same
// failure mode renderBody's component bound exists to prevent.
func TestTitleIsBoundedForOverlongKeys(t *testing.T) {
	long := postureTheme(strings.Repeat("C-0016-", 200), "apps/Deployment/web")

	title := renderTitle(long)
	if n := len([]rune(title)); n > githubIssueTitleLimit {
		t.Errorf("title is %d runes, over GitHub's %d limit", n, githubIssueTitleLimit)
	}

	if !strings.HasSuffix(title, "…") {
		t.Errorf("truncation is not disclosed: %q", title)
	}

	// Anti-churn: the bounded title must be byte-stable across renders, or
	// every run becomes an update.
	if renderTitle(long) != title {
		t.Error("a truncated title is not byte-stable across renders")
	}

	// A multi-byte key must not be cut mid-rune — a byte cut would emit U+FFFD
	// and differ from the live title every run.
	wide := postureTheme(strings.Repeat("é", 400), "apps/Deployment/web")
	if strings.ContainsRune(renderTitle(wide), '�') {
		t.Error("title truncation split a multi-byte rune")
	}

	// CONTROL — a title under the bound must pass through untouched, so the
	// truncation above is attributable to length.
	short := postureTheme("C-0016", "apps/Deployment/web")
	if got := renderTitle(short); strings.HasSuffix(got, "…") || got != sanitizeForIssue(short.Title()) {
		t.Errorf("control did not flip: a short title was altered: %q", got)
	}
}
