package main

import (
	"bytes"
	"errors"
	"fmt"
	"strings"
	"testing"
)

// postureTheme and cveTheme are the two shapes the reconciler sees.
func postureTheme(key string, components ...string) theme {
	return theme{
		Kind:       string(surfacePosture),
		Key:        key,
		Severity:   "High",
		Components: components,
		Count:      len(components),
	}
}

func cveTheme(key string, total int, components ...string) theme {
	return theme{
		Kind:       string(surfaceCVE),
		Key:        key,
		Severity:   key,
		Components: components,
		Count:      len(components),
		Total:      total,
	}
}

// goldenPostureBody is the EXACT body a previous run wrote for
// postureTheme("C-0016", "apps/Deployment/web").
//
// It is a literal rather than a renderBody() call, and that is the whole point.
// The zero-write property below asserts that an unchanged theme renders
// identically to what is already filed; if the existing body were produced by
// calling renderBody in the test, the comparison would hold for ANY renderBody
// — including one that embedded a timestamp, which is precisely the instability
// that would turn every run into an update. Pinning the bytes here means a
// format drift fails this test instead of silently churning the backlog.
const goldenPostureBody = "> 🤖 Generated by the Agentic Engineer\n\n" +
	"<!-- kubescape-backlog-bridge:fingerprint=" + goldenPostureFingerprint + " -->\n\n" +
	"Filed automatically from live Kubescape findings by " +
	"`scripts/kubescape-backlog-bridge`. Part of #2854.\n\n" +
	"**Surface:** posture\n" +
	"**Severity:** High\n" +
	"\n**Affected components (1):**\n\n" +
	"- `apps/Deployment/web`\n" +
	"\nThis issue is reconciled automatically: it is updated when the affected set " +
	"changes and closed when the finding is gone. Edit the title or body only if you are " +
	"willing to have it overwritten — the fingerprint comment above is what identifies it.\n"

// goldenPostureFingerprint pins sha256("posture|C-0016")[:16], computed
// independently of this package: `printf 'posture|C-0016' | shasum -a 256`.
const goldenPostureFingerprint = "43379dbb9d5d9566"

const goldenPostureTitle = "security(posture): C-0016 fails"

func TestRenderMatchesGolden(t *testing.T) {
	th := postureTheme("C-0016", "apps/Deployment/web")

	if got := th.Fingerprint(); got != goldenPostureFingerprint {
		t.Fatalf("fingerprint drifted: got %q want %q", got, goldenPostureFingerprint)
	}

	if got := renderTitle(th); got != goldenPostureTitle {
		t.Errorf("title drifted:\n got %q\nwant %q", got, goldenPostureTitle)
	}

	if got := renderBody(th); got != goldenPostureBody {
		t.Errorf("body drifted:\n got %q\nwant %q", got, goldenPostureBody)
	}
}

// TestRenderIsDeterministic guards the anti-churn guarantee at its source: two
// renders of one theme must be byte-identical, so an unchanged cluster writes
// nothing. A component set is deliberately supplied in a different ORDER each
// time, because the reconciler compares rendered text and any order-sensitivity
// here would surface as a permanent update loop rather than as a failure.
func TestRenderIsDeterministic(t *testing.T) {
	a := renderBody(postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg"))
	b := renderBody(postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg"))

	if a != b {
		t.Fatalf("renderBody is not deterministic:\n%q\n%q", a, b)
	}
}

func trackedPosture(number int, open bool) backlogEntry {
	return backlogEntry{Number: number, Title: goldenPostureTitle, Body: goldenPostureBody, Open: open}
}

// TestUnchangedStateProducesNoWrites is the acceptance criterion "no issue
// spam: unchanged cluster state produces zero writes", asserted as a property.
func TestUnchangedStateProducesNoWrites(t *testing.T) {
	themes := []theme{postureTheme("C-0016", "apps/Deployment/web")}
	existing := []backlogEntry{trackedPosture(41, true)}

	p, err := planWrites(themes, existing, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("unchanged state planned %d write(s): %+v", len(p.Actions), p.Actions)
	}

	// CONTROL — the assertion above must be capable of failing. One byte of
	// drift in the tracked body has to produce an update; if it does not, the
	// comparison is vacuous and the empty plan above proved nothing.
	drifted := []backlogEntry{{
		Number: 41,
		Title:  goldenPostureTitle,
		Body:   strings.Replace(goldenPostureBody, "apps/Deployment/web", "apps/Deployment/api", 1),
		Open:   true,
	}}

	if drifted[0].Body == goldenPostureBody {
		t.Fatal("control is inert: the substitution did not change the body")
	}

	ctrl, err := planWrites(themes, drifted, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "update" {
		t.Fatalf("control did not flip: want one update, got %+v", ctrl.Actions)
	}
}

func TestUntrackedThemeIsCreated(t *testing.T) {
	p, err := planWrites([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		nil, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "create" {
		t.Fatalf("want one create, got %+v", p.Actions)
	}

	if p.Actions[0].Number != 0 {
		t.Errorf("a create must carry no issue number, got #%d", p.Actions[0].Number)
	}
}

// TestReturningThemeReopensRatherThanRecreates pins the property that keeps
// "at most one open issue per theme" true across a resolve/regress cycle.
func TestReturningThemeReopensRatherThanRecreates(t *testing.T) {
	p, err := planWrites([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]backlogEntry{trackedPosture(41, false)}, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "reopen" || p.Actions[0].Number != 41 {
		t.Fatalf("want one reopen of #41, got %+v", p.Actions)
	}
}

// TestAffectedSetChangeUpdatesTheSameIssue proves a workload joining a theme
// lands on the ORIGINAL issue. The fingerprint excludes the component set
// precisely so this is an update; were it included, this would be a create and
// the old issue would be stranded.
func TestAffectedSetChangeUpdatesTheSameIssue(t *testing.T) {
	grown := postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg")

	p, err := planWrites([]theme{grown},
		[]backlogEntry{trackedPosture(41, true)}, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(p.Actions) != 1 || p.Actions[0].Kind != "update" || p.Actions[0].Number != 41 {
		t.Fatalf("want one update of #41, got %+v", p.Actions)
	}

	if !strings.Contains(p.Actions[0].Body, "db/StatefulSet/pg") {
		t.Error("the update body does not carry the newly affected component")
	}
}

// TestCloseRequiresInputsComplete is the destructive half's gate. A run that
// cannot assert it examined every object must never mark a finding resolved.
func TestCloseRequiresInputsComplete(t *testing.T) {
	existing := []backlogEntry{trackedPosture(41, true)}

	p, err := planWrites(nil, existing, []surface{surfacePosture}, false)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("a partial run planned writes: %+v", p.Actions)
	}

	// CONTROL — with the assertion supplied, and nothing else changed, the same
	// input must close. Without this the test above would pass for a planner
	// that never closes at all.
	ctrl, err := planWrites(nil, existing, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "close" || ctrl.Actions[0].Number != 41 {
		t.Fatalf("control did not flip: want one close of #41, got %+v", ctrl.Actions)
	}
}

// TestCloseIsScopedToExaminedSurfaces stops a posture-only sweep from resolving
// every CVE finding it never looked at.
func TestCloseIsScopedToExaminedSurfaces(t *testing.T) {
	cve := cveTheme("Critical", 3, "apps/Deployment/web")
	cveEntry := backlogEntry{
		Number: 77,
		Title:  renderTitle(cve),
		Body:   renderBody(cve),
		Open:   true,
	}

	p, err := planWrites(nil, []backlogEntry{cveEntry}, []surface{surfacePosture}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("a posture-only run planned CVE writes: %+v", p.Actions)
	}

	// CONTROL — the same entry, with its own surface examined, must close.
	ctrl, err := planWrites(nil, []backlogEntry{cveEntry}, []surface{surfaceCVE}, true)
	if err != nil {
		t.Fatalf("control planWrites: %v", err)
	}

	if len(ctrl.Actions) != 1 || ctrl.Actions[0].Kind != "close" {
		t.Fatalf("control did not flip: want one close, got %+v", ctrl.Actions)
	}
}

// TestUnreadableSurfaceIsNeverClosed is the fail-closed direction: a tracked
// issue whose surface line was edited away must be left alone rather than
// resolved, because the cost of a wrong close is a live finding marked done.
func TestUnreadableSurfaceIsNeverClosed(t *testing.T) {
	mangled := trackedPosture(41, true)
	mangled.Body = strings.Replace(mangled.Body, "**Surface:** posture", "**Surface:** ???", 1)

	if !strings.Contains(mangled.Body, "???") {
		t.Fatal("control is inert: the surface line was not mangled")
	}

	p, err := planWrites(nil, []backlogEntry{mangled}, []surface{surfacePosture, surfaceCVE}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if !p.empty() {
		t.Fatalf("an entry with an unreadable surface was acted on: %+v", p.Actions)
	}
}

func TestDuplicateFingerprintIsRefused(t *testing.T) {
	_, err := planWrites(nil,
		[]backlogEntry{trackedPosture(41, true), trackedPosture(42, true)},
		[]surface{surfacePosture}, true)

	if !errors.Is(err, errAmbiguousEntry) {
		t.Fatalf("want errAmbiguousEntry, got %v", err)
	}
}

func TestUnreadableFingerprintIsRefused(t *testing.T) {
	entry := trackedPosture(41, true)
	entry.Body = "> 🤖 Generated by the Agentic Engineer\n\nno marker here\n"

	_, err := planWrites(nil, []backlogEntry{entry}, []surface{surfacePosture}, true)

	if !errors.Is(err, errMissingFingerprint) {
		t.Fatalf("want errMissingFingerprint, got %v", err)
	}
}

// TestPlanOrderIsStable keeps two runs on identical state emitting an identical
// action list, so a diff of two runs is meaningful evidence.
func TestPlanOrderIsStable(t *testing.T) {
	themes := []theme{
		cveTheme("Critical", 2, "a/Deployment/x"),
		postureTheme("C-0017", "b/Deployment/y"),
		postureTheme("C-0016", "a/Deployment/x"),
	}

	first, err := planWrites(themes, nil, []surface{surfacePosture, surfaceCVE}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	shuffled := []theme{themes[2], themes[0], themes[1]}

	second, err := planWrites(shuffled, nil, []surface{surfacePosture, surfaceCVE}, true)
	if err != nil {
		t.Fatalf("planWrites: %v", err)
	}

	if len(first.Actions) != 3 {
		t.Fatalf("want 3 creates, got %+v", first.Actions)
	}

	for i := range first.Actions {
		if first.Actions[i].Title != second.Actions[i].Title {
			t.Fatalf("action order depends on input order at %d: %q vs %q",
				i, first.Actions[i].Title, second.Actions[i].Title)
		}
	}
}

// fakeStore records every call so a test can assert on writes that did NOT
// happen — the property an inspected plan cannot prove.
type fakeStore struct {
	entries []backlogEntry
	calls   []string
	nextNum int
	failOn  string
}

func (f *fakeStore) list() ([]backlogEntry, error) {
	if f.failOn == "list" {
		return nil, errors.New("boom")
	}

	return f.entries, nil
}

func (f *fakeStore) create(title, _ string) (int, error) {
	if f.failOn == "create" {
		return 0, errors.New("boom")
	}

	f.nextNum++
	f.calls = append(f.calls, "create:"+title)

	return f.nextNum, nil
}

func (f *fakeStore) update(number int, _, _ string) error {
	f.calls = append(f.calls, fmt.Sprintf("update:%d", number))

	return nil
}

func (f *fakeStore) reopen(number int, _, _ string) error {
	f.calls = append(f.calls, fmt.Sprintf("reopen:%d", number))

	return nil
}

func (f *fakeStore) close(number int, _ string) error {
	f.calls = append(f.calls, fmt.Sprintf("close:%d", number))

	return nil
}

// TestReconcileWritesNothingOnUnchangedState closes the loop end-to-end: not
// merely an empty plan, but a driver that issues no mutating call at all.
func TestReconcileWritesNothingOnUnchangedState(t *testing.T) {
	store := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	var out bytes.Buffer

	err := reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]surface{surfacePosture}, true, store, &out)
	if err != nil {
		t.Fatalf("reconcile: %v", err)
	}

	if len(store.calls) != 0 {
		t.Fatalf("unchanged state issued writes: %v", store.calls)
	}

	if !strings.Contains(out.String(), "no changes") {
		t.Errorf("run said nothing about doing nothing: %q", out.String())
	}

	// CONTROL — a changed theme through the SAME path must write, so the
	// silence above is a decision and not a broken driver.
	ctrlStore := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	err = reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web", "db/StatefulSet/pg")},
		[]surface{surfacePosture}, true, ctrlStore, &bytes.Buffer{})
	if err != nil {
		t.Fatalf("control reconcile: %v", err)
	}

	if len(ctrlStore.calls) != 1 || ctrlStore.calls[0] != "update:41" {
		t.Fatalf("control did not flip: want [update:41], got %v", ctrlStore.calls)
	}
}

// TestWithheldCloseIsDisclosed pins the honesty property found while exercising
// the real binary: a gated run declined to close a stale entry and reported
// only "no changes", which reads as a reconciled backlog. A withheld action and
// a completed one must not render identically.
func TestWithheldCloseIsDisclosed(t *testing.T) {
	store := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}

	var out bytes.Buffer

	// No themes: the finding is gone. No -inputs-complete: closing is gated.
	if err := reconcile(nil, []surface{surfacePosture}, false, store, &out); err != nil {
		t.Fatalf("reconcile: %v", err)
	}

	if len(store.calls) != 0 {
		t.Fatalf("a gated run wrote: %v", store.calls)
	}

	if !strings.Contains(out.String(), "left OPEN") {
		t.Errorf("the withheld close was not disclosed: %q", out.String())
	}

	// CONTROL — a run with nothing withheld must NOT emit the note, or the
	// disclosure is unconditional boilerplate rather than a signal.
	var ctrl bytes.Buffer

	ctrlStore := &fakeStore{entries: []backlogEntry{trackedPosture(41, true)}}
	if err := reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]surface{surfacePosture}, false, ctrlStore, &ctrl); err != nil {
		t.Fatalf("control reconcile: %v", err)
	}

	if strings.Contains(ctrl.String(), "left OPEN") {
		t.Errorf("the note fired with nothing withheld: %q", ctrl.String())
	}
}

func TestReconcileStopsAtFirstFailure(t *testing.T) {
	store := &fakeStore{failOn: "create"}

	err := reconcile([]theme{postureTheme("C-0016", "apps/Deployment/web")},
		[]surface{surfacePosture}, true, store, &bytes.Buffer{})

	if !errors.Is(err, errWriteFailed) {
		t.Fatalf("want errWriteFailed, got %v", err)
	}
}

func TestParseIssueNumber(t *testing.T) {
	n, err := parseIssueNumber("https://github.com/devantler-tech/platform/issues/2899\n")
	if err != nil {
		t.Fatalf("parseIssueNumber: %v", err)
	}

	if n != 2899 {
		t.Errorf("got #%d want #2899", n)
	}

	if _, err := parseIssueNumber("Creating issue in devantler-tech/platform\n"); err == nil {
		t.Error("want an error when no issue URL is present")
	}
}

// TestListRefusesTruncatedPage pins the duplicate-storm guard: a listing that
// reaches the CLI's own ceiling cannot be distinguished from a complete one, so
// it is refused rather than reconciled against.
func TestListRefusesTruncatedPage(t *testing.T) {
	var page []string
	for i := range listLimit {
		page = append(page, fmt.Sprintf(`{"number":%d,"title":"t","body":"b","state":"OPEN"}`, i+1))
	}

	store := &ghStore{repo: "o/r", run: func(...string) ([]byte, error) {
		return []byte("[" + strings.Join(page, ",") + "]"), nil
	}}

	if _, err := store.list(); !errors.Is(err, errWriteFailed) {
		t.Fatalf("a full page was accepted as complete: %v", err)
	}

	// CONTROL — one fewer issue is not truncated and must be accepted.
	store.run = func(...string) ([]byte, error) {
		return []byte("[" + strings.Join(page[:listLimit-1], ",") + "]"), nil
	}

	entries, err := store.list()
	if err != nil {
		t.Fatalf("control list: %v", err)
	}

	if len(entries) != listLimit-1 {
		t.Fatalf("control returned %d entries, want %d", len(entries), listLimit-1)
	}
}

// TestListMapsStateToOpen guards the reopen path's input: `gh` emits OPEN/CLOSED
// in upper case, and reading it case-sensitively would mark every tracked issue
// closed and turn every update into a reopen.
func TestListMapsStateToOpen(t *testing.T) {
	store := &ghStore{repo: "o/r", run: func(...string) ([]byte, error) {
		return []byte(`[{"number":1,"title":"a","body":"b","state":"OPEN"},` +
			`{"number":2,"title":"c","body":"d","state":"CLOSED"}]`), nil
	}}

	entries, err := store.list()
	if err != nil {
		t.Fatalf("list: %v", err)
	}

	if !entries[0].Open || entries[1].Open {
		t.Fatalf("state mapping wrong: %+v", entries)
	}
}
