apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arc-controller
  namespace: arc-systems
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/part-of: gha-rs-controller
