apiVersion: v1
kind: Secret
metadata:
    name: umami-app
    namespace: umami
type: Opaque
stringData:
    app-secret: ENC[AES256_GCM,data:Guhb2dHEWWxhMqyflIunvq7SeeV58gwNcQhLs81OqUUEMH/R3Kk2WNxravPz+a32V2jXVBcpF6fki3dq7UGxHA==,iv:ZSO2w+ebS9EH8bTby+4Cmi2T0Dv6sqfKBvQjNr6Bq40=,tag:cuLBvA5AuZV6eVmO7HzDHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RHNkU0k4SHZwaHBBMlRH
            NWplNjBYSy84a2c4cEIvNGFaOWhDNExGMEc0CkxaajlDZWZ4YmF0RlU4WjJ1SXNN
            aHMweW9YRHp2bWpER2ZkM3l0ZXNodE0KLS0tIGU4b0JpNDNOUS9UZFZXeHlFNmRa
            UWM0OVA5eHI3d2d0NGhVR3Q1MkdJZkkK9SBlgjeVY2IU+zq2qZEVoTdXv5Q4DY8o
            JUIcpd6UoDuzM/TMXMjVT7EdKTF7eBW95bv/gsqnHwQiBLONVv4gTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZW5aQTBmY25wem4rK0Yz
            dnkyZ1d0Yll1L0w0Ym5tdWlHT0JKM2VjNjJRCnIxd0hiWjUxbmFBdXMyUHRGdk9p
            YXpxWEFRd05EbXV2NWlLKzlZb2JrTkEKLS0tIHZFWVZtaFN0T2RUWjVIRVhXNlJT
            L2hVR0NUejNSSWZ6dmZ0by8wc2JvQk0KEY8bBYMWevejO0gU4UOb7qA7r+VLwxog
            Dm3K0qeG5w35SiO7P7bSa4+K7IDxdAAfbUbynJOL3b0ocyPZau5jPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T22:05:09Z"
    mac: ENC[AES256_GCM,data:pLBtrCnZBzpfsrvg0DbLzAFF5PWlmsUMNUWIoIxZQ4ovzBgu5w4tDGvRaxuzCzmB4wc9KLLEQqJXK7rNaXHo2UlGdPmYy30K8hGZuUIMRTAi2XCHS4+wMMRbgEU6OGYrxVj4ObdRerTEy9OLGcKnabnzRnC8uk3PLkhXCgx8dgg=,iv:J1FLSDiOfl1pH/hVo/pi0uJH5CWvIwR6TET0vExTapw=,tag:x+wVJsojR9EG+jSdJJLIfA==,type:str]
    version: 3.13.1
