---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - network-policy.yaml
  - secret-store.yaml
  - provider-config.yaml
  - policy-eks-ci-smoke-boundary.yaml
  - role-eks-ci.yaml
  - external-secret.yaml
  - oci-repository.yaml
  - flux-kustomization.yaml
