apiVersion: v1
kind: Secret
metadata:
    name: variables-cluster
    namespace: flux-system
stringData:
    dex_client_secret: ENC[AES256_GCM,data:RkaU1YOgpfRkj0T+ibOjftzro+w=,iv:uLeA+HaApXEM8xf0PJORHHjvWfHbhXJDTPyg43SrCUg=,tag:kViXk4lSyURVvoAP25ZxsA==,type:str]
    flux_web_client_secret: ENC[AES256_GCM,data:BkpU+IQq4srfTGWaSwOyd8ojkHZTkbdJ1HSM2MOAGf4=,iv:1jOmNhicI8/2r1Dx7vNkM91rY+APrIDBfMoFR6rjBAo=,tag:25hIq51f7V8Tb39ZENCwiw==,type:str]
    github_app_client_secret: ENC[AES256_GCM,data:nqSBfg3Ty+vAjyo4GKmqIumowMVCXV2EciTI4ieq/ETZYUjtf9HTyA==,iv:uyOuX1CgrOoKcYJgq3eaJsF/3e83xAY62k0MGYqT//o=,tag:fkIIA6XUJK9pHEjSrvKSmA==,type:str]
    oauth2_proxy_cookie_secret: ENC[AES256_GCM,data:JbqAbb2gRfXhD32bibQWen3VE8XLjAYtWxLnowW9kugEgPte5qPdAFBxHBQ=,iv:wpX4TJwS6FURhqO6t6WyA6x/yBuZMPofGwDrtLNk1Nk=,tag:V8eawWX2GKaGKI06X3V80w==,type:str]
sops:
    age:
        - recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVVROeFpqUVNZMXJ0Skhh
            VklicUVNVVZSQ0dEYlQrRlZKekxlTisrQkYwCkRZdWtoU0FFbjNWbzdmcjRjNDF0
            eDN3MDhydjVXUnh1dVptVlRoa0c0SzQKLS0tIHQrK3V6MWNZQnRLTlNqZWhwdjBG
            SjBVZURpUkc4eGJ4eFFFcGV2SUJuVkEKPYKtlz5eBFjChW02JeKqJxviRkJIGU9t
            GrLSSCJvxfCt1dUEkef2/lwSaLIggjtvSJLOxNa7hqQCI86Di5trxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T21:27:28Z"
    mac: ENC[AES256_GCM,data:WgmqbwRpL4BIyCJ0vo3//EdiucbY0V/xyPddqdMSIBvrSFxL/CGw7UQCHXBkP830d6iLg6/xC/iJ33XftOQ+Dcajn8+/UNwaR7OWyXuYO9oeL05zpZtX6kvvujAVBTdUhjnjtknhwyB3UuQry5cLEVM8KfmrNTjYJtbIf4lhRYk=,iv:Fc3X/jLWIb9S5ltZn4eBbCjIUX5YUix9DH3PhBMN6Rc=,tag:9oSeE0ykYx4EZ3CoBW+x9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
