apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: origin-ca-issuer
  namespace: cert-manager
spec:
  interval: 10m
  url: oci://ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer
  ref:
    tag: 0.6.4
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
