apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: world-at-ruin
  namespace: world-at-ruin
spec:
  provider:
    vault:
      server: "http://openbao-active.openbao.svc.cluster.local:8200"
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: app-world-at-ruin
          serviceAccountRef:
            name: world-at-ruin
