apiVersion: v1
kind: Secret
metadata:
    name: variables-base
    namespace: flux-system
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:ADfRMMzGdOp9oT0wAMLCvlP4QA/3I2S7Ts5LcMF0VZnb4+7nTTFTMLWSwn1k27Fem87bhLA=,iv:narD4cOgsbo8VyEeT4X00wcPFigDSDSHUwAQKjhZABc=,tag:uFKv6ZiBOk03c0YUI2wTbQ==,type:str]
    r2_access_key_id: ENC[AES256_GCM,data:SbBQvC8ex2M10JHV6ogBFkvN+13ZNQc5hS7U,iv:5k7bOd/q75c146+HvEUZGsVLPDNc5qDE/u2KFGfs/3Y=,tag:DKrOyTVC6R0AMfBhiCZFAg==,type:str]
    r2_secret_access_key: ENC[AES256_GCM,data:PdhgQ1d1pDW1lLcXasYG2roEG8qapUHpHM/goE+V1w==,iv:g3QCozVlZMEBRfMhVvfSf5i8lYK+3hnFPJ+fEjSJz4s=,tag:UJL+z0bQ2C7f71XJSdWCvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ0dKVzlWUHFGZjkzT2Fa
            MDA2TWpjZ3R4Sm1id1MwaXJDcC8vZ2VyMDBvCnVzQ2R6NVN5QTRPOTRPUlFXK3dl
            dFZaTFRmSVVKRWk5T2JlMjdnUFVMcVUKLS0tIG5lRW9VL2k4bkQ2WHc3aVNUT0JN
            b09tc1BKcC9ManZIcjRNRWdNUnRlQkEKyHHYlCkiNozfc9igMjtUuS480W4ZZ/bm
            zQMzqfYZzRcOgvQn/ZN6UfI1pJvP+5gyWCyn2pszWDMp4Vhwu9oBxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14skmde00w0ps6u8asm4rdqwpktr5m5pq84070yzwvjjmcyfnl4ushfn5uq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZzdvcGZBWlUrU3dVVUxa
            VkRQcC9DVExOd3BDWjI1SHBETUJyS1FKTkRjCjJFZExqMUxxSjhVTFFtTUxYV1U1
            N2V2UzJKWXpUZzBlaUhlS2o5T3M1eG8KLS0tIGx5OE1GZzIwaXpPMmVtMmNqdDV5
            bkdBL2M2NGRmU0UzdVhhNmQyS1FrOHcKntnuB5lrMYQFoqWt2TdDcy8hYp2h8pgS
            AF6/Z85IymNcYOAoOF/VUt41wG8OvYcTBo7P+0XdwxRs7F+EQh+9gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rk6fs67kly3h4zux5za429z3grjtvs8vcunav4sa28pxk738najsk8wgs6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-18T22:09:18Z"
    mac: ENC[AES256_GCM,data:c06gQllC6M2Nvb3zHmLdk9wMVRgY72ZjxQOwMmj2X5S3gQz5EkL7qZs+gw9MQgOYE8TdMXmRc0bhkxIL6nanrVpOdqEzTMZtcdXbmIP3JpyV+KVreX80hP0ovF8HaYHkf8C7cmZ0QYjCDLdbNw9rWCAeXUEX7vcvAtdvf5+Vf1Q=,iv:Ew3Jw1tbVyaMg0r02W9F+zl6qyVaBNvfo3zmsaYBG+w=,tag:MjcQQvHMSt0rp3KL4KLOxA==,type:str]
    version: 3.12.2
