apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opencost-usage-scraper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencost-usage-scraper
subjects:
  - kind: ServiceAccount
    name: opencost-usage-scraper
    namespace: opencost
