name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/actions/.github/workflows/create-release.yaml@5de934e076503c897d43d85680406f8d1d9356b7 # v10.0.0
    permissions:
      contents: write # create releases and tags
      issues: write # comment on related issues
      pull-requests: write # comment on related PRs
      id-token: write # provenance signing
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
