name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/create-release.yaml@1d1a4ded35afff36f18dca06ec20b9fc5fe93bea # v3.5.0
    permissions:
      contents: write # create releases and tags
      issues: write # comment on related issues
      pull-requests: write # comment on related PRs
      id-token: write # provenance signing
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
