name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/create-release.yaml@e5eea909adaf782180f325c37a1311661b25bbb7 # v5.6.0
    permissions:
      contents: write # create releases and tags
      issues: write # comment on related issues
      pull-requests: write # comment on related PRs
      id-token: write # provenance signing
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
