name: Sync Cluster Policies

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'k8s/bases/infrastructure/cluster-policies/samples/**'

permissions: {}

jobs:
  sync-policies:
    uses: devantler-tech/reusable-workflows/.github/workflows/sync-cluster-policies.yaml@6b44cfb837e545a8179b0cc97a63b7c694cb9287 # v5.5.7
    with:
      kyverno-policies-dir: k8s/bases/infrastructure/cluster-policies/samples
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
