name: Sync Cluster Policies

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "k8s/bases/infrastructure/cluster-policies/samples/**"

permissions: {}

jobs:
  sync-policies:
    uses: devantler-tech/actions/.github/workflows/sync-cluster-policies.yaml@efdff74933a4c137d5b442f54687882a24de88db # v13.6.3
    with:
      kyverno-policies-dir: k8s/bases/infrastructure/cluster-policies/samples
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
