name: Sync Cluster Policies

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'k8s/bases/infrastructure/cluster-policies/samples/**'

permissions: {}

jobs:
  sync-policies:
    uses: devantler-tech/actions/.github/workflows/sync-cluster-policies.yaml@bd78711c15f1e473e3ba75b0d5e8aece26019660 # v8.0.1
    with:
      kyverno-policies-dir: k8s/bases/infrastructure/cluster-policies/samples
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
