name: "TODOs"
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/scan-for-todo-comments.yaml@e5eea909adaf782180f325c37a1311661b25bbb7 # v5.6.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
