name: "TODOs"
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/scan-for-todo-comments.yaml@b748f68a0d14ad477cb9610a6d1f958bf75e91dc # v5.2.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
